// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/mdiningapi.proto

package mdiningapi

import (
	mdining "github.com/MichiganDiningAPI/proto/mdining"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiningHallsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DiningHallGroup []*DiningHallGroup     `protobuf:"bytes,1,rep,name=diningHallGroup,proto3" json:"diningHallGroup,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDiningHallsReply) Reset() {
	*x = GetDiningHallsReply{}
	mi := &file_proto_mdiningapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiningHallsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiningHallsReply) ProtoMessage() {}

func (x *GetDiningHallsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiningHallsReply.ProtoReflect.Descriptor instead.
func (*GetDiningHallsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiningHallsReply) GetDiningHallGroup() []*DiningHallGroup {
	if x != nil {
		return x.DiningHallGroup
	}
	return nil
}

type DiningHallGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DiningHall    []*mdining.DiningHall  `protobuf:"bytes,2,rep,name=diningHall,proto3" json:"diningHall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHallGroup) Reset() {
	*x = DiningHallGroup{}
	mi := &file_proto_mdiningapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHallGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHallGroup) ProtoMessage() {}

func (x *DiningHallGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHallGroup.ProtoReflect.Descriptor instead.
func (*DiningHallGroup) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{1}
}

func (x *DiningHallGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiningHallGroup) GetDiningHall() []*mdining.DiningHall {
	if x != nil {
		return x.DiningHall
	}
	return nil
}

type GetMenuBaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          []*MenuBase            `protobuf:"bytes,1,rep,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuBaseReply) Reset() {
	*x = GetMenuBaseReply{}
	mi := &file_proto_mdiningapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuBaseReply) ProtoMessage() {}

func (x *GetMenuBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuBaseReply.ProtoReflect.Descriptor instead.
func (*GetMenuBaseReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetMenuBaseReply) GetMenu() []*MenuBase {
	if x != nil {
		return x.Menu
	}
	return nil
}

type MenuBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FormattedDate string                 `protobuf:"bytes,4,opt,name=formattedDate,proto3" json:"formattedDate,omitempty"`
	RatingCount   int32                  `protobuf:"varint,5,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	RatingScore   int32                  `protobuf:"varint,6,opt,name=ratingScore,proto3" json:"ratingScore,omitempty"`
	HasCategories bool                   `protobuf:"varint,7,opt,name=hasCategories,proto3" json:"hasCategories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuBase) Reset() {
	*x = MenuBase{}
	mi := &file_proto_mdiningapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuBase) ProtoMessage() {}

func (x *MenuBase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuBase.ProtoReflect.Descriptor instead.
func (*MenuBase) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{3}
}

func (x *MenuBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuBase) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MenuBase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuBase) GetFormattedDate() string {
	if x != nil {
		return x.FormattedDate
	}
	return ""
}

func (x *MenuBase) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *MenuBase) GetRatingScore() int32 {
	if x != nil {
		return x.RatingScore
	}
	return 0
}

func (x *MenuBase) GetHasCategories() bool {
	if x != nil {
		return x.HasCategories
	}
	return false
}

type GetMenuDetailsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          []*MenuDetail          `protobuf:"bytes,1,rep,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuDetailsReply) Reset() {
	*x = GetMenuDetailsReply{}
	mi := &file_proto_mdiningapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuDetailsReply) ProtoMessage() {}

func (x *GetMenuDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuDetailsReply.ProtoReflect.Descriptor instead.
func (*GetMenuDetailsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuDetailsReply) GetMenu() []*MenuDetail {
	if x != nil {
		return x.Menu
	}
	return nil
}

type MenuDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	FormattedDate string                 `protobuf:"bytes,3,opt,name=formattedDate,proto3" json:"formattedDate,omitempty"`
	RatingCount   int32                  `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	RatingScore   int32                  `protobuf:"varint,5,opt,name=ratingScore,proto3" json:"ratingScore,omitempty"`
	HasCategories bool                   `protobuf:"varint,6,opt,name=hasCategories,proto3" json:"hasCategories,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Category      []*mdining.Category    `protobuf:"bytes,8,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuDetail) Reset() {
	*x = MenuDetail{}
	mi := &file_proto_mdiningapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuDetail) ProtoMessage() {}

func (x *MenuDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuDetail.ProtoReflect.Descriptor instead.
func (*MenuDetail) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi_proto_rawDescGZIP(), []int{5}
}

func (x *MenuDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuDetail) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MenuDetail) GetFormattedDate() string {
	if x != nil {
		return x.FormattedDate
	}
	return ""
}

func (x *MenuDetail) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *MenuDetail) GetRatingScore() int32 {
	if x != nil {
		return x.RatingScore
	}
	return 0
}

func (x *MenuDetail) GetHasCategories() bool {
	if x != nil {
		return x.HasCategories
	}
	return false
}

func (x *MenuDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuDetail) GetCategory() []*mdining.Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_proto_mdiningapi_proto protoreflect.FileDescriptor

const file_proto_mdiningapi_proto_rawDesc = "" +
	"\n" +
	"\x16proto/mdiningapi.proto\x12\n" +
	"mdiningapi\x1a\x17proto/dininghalls.proto\x1a\x11proto/items.proto\x1a\x1dproto/filterableentries.proto\x1a\x10proto/menu.proto\"\\\n" +
	"\x13GetDiningHallsReply\x12E\n" +
	"\x0fdiningHallGroup\x18\x01 \x03(\v2\x1b.mdiningapi.DiningHallGroupR\x0fdiningHallGroup\"Z\n" +
	"\x0fDiningHallGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\n" +
	"diningHall\x18\x02 \x03(\v2\x13.mdining.DiningHallR\n" +
	"diningHall\"<\n" +
	"\x10GetMenuBaseReply\x12(\n" +
	"\x04menu\x18\x01 \x03(\v2\x14.mdiningapi.MenuBaseR\x04menu\"\xe4\x01\n" +
	"\bMenuBase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\rformattedDate\x18\x04 \x01(\tR\rformattedDate\x12 \n" +
	"\vratingCount\x18\x05 \x01(\x05R\vratingCount\x12 \n" +
	"\vratingScore\x18\x06 \x01(\x05R\vratingScore\x12$\n" +
	"\rhasCategories\x18\a \x01(\bR\rhasCategories\"A\n" +
	"\x13GetMenuDetailsReply\x12*\n" +
	"\x04menu\x18\x01 \x03(\v2\x16.mdiningapi.MenuDetailR\x04menu\"\x95\x02\n" +
	"\n" +
	"MenuDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12$\n" +
	"\rformattedDate\x18\x03 \x01(\tR\rformattedDate\x12 \n" +
	"\vratingCount\x18\x04 \x01(\x05R\vratingCount\x12 \n" +
	"\vratingScore\x18\x05 \x01(\x05R\vratingScore\x12$\n" +
	"\rhasCategories\x18\x06 \x01(\bR\rhasCategories\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12-\n" +
	"\bcategory\x18\b \x03(\v2\x11.mdining.CategoryR\bcategoryb\x06proto3"

var (
	file_proto_mdiningapi_proto_rawDescOnce sync.Once
	file_proto_mdiningapi_proto_rawDescData []byte
)

func file_proto_mdiningapi_proto_rawDescGZIP() []byte {
	file_proto_mdiningapi_proto_rawDescOnce.Do(func() {
		file_proto_mdiningapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mdiningapi_proto_rawDesc), len(file_proto_mdiningapi_proto_rawDesc)))
	})
	return file_proto_mdiningapi_proto_rawDescData
}

var file_proto_mdiningapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_mdiningapi_proto_goTypes = []any{
	(*GetDiningHallsReply)(nil), // 0: mdiningapi.GetDiningHallsReply
	(*DiningHallGroup)(nil),     // 1: mdiningapi.DiningHallGroup
	(*GetMenuBaseReply)(nil),    // 2: mdiningapi.GetMenuBaseReply
	(*MenuBase)(nil),            // 3: mdiningapi.MenuBase
	(*GetMenuDetailsReply)(nil), // 4: mdiningapi.GetMenuDetailsReply
	(*MenuDetail)(nil),          // 5: mdiningapi.MenuDetail
	(*mdining.DiningHall)(nil),  // 6: mdining.DiningHall
	(*mdining.Category)(nil),    // 7: mdining.Category
}
var file_proto_mdiningapi_proto_depIdxs = []int32{
	1, // 0: mdiningapi.GetDiningHallsReply.diningHallGroup:type_name -> mdiningapi.DiningHallGroup
	6, // 1: mdiningapi.DiningHallGroup.diningHall:type_name -> mdining.DiningHall
	3, // 2: mdiningapi.GetMenuBaseReply.menu:type_name -> mdiningapi.MenuBase
	5, // 3: mdiningapi.GetMenuDetailsReply.menu:type_name -> mdiningapi.MenuDetail
	7, // 4: mdiningapi.MenuDetail.category:type_name -> mdining.Category
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_mdiningapi_proto_init() }
func file_proto_mdiningapi_proto_init() {
	if File_proto_mdiningapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mdiningapi_proto_rawDesc), len(file_proto_mdiningapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mdiningapi_proto_goTypes,
		DependencyIndexes: file_proto_mdiningapi_proto_depIdxs,
		MessageInfos:      file_proto_mdiningapi_proto_msgTypes,
	}.Build()
	File_proto_mdiningapi_proto = out.File
	file_proto_mdiningapi_proto_goTypes = nil
	file_proto_mdiningapi_proto_depIdxs = nil
}
