// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/dininghalls.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiningHalls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiningHalls   []*DiningHall          `protobuf:"bytes,1,rep,name=diningHalls,proto3" json:"diningHalls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHalls) Reset() {
	*x = DiningHalls{}
	mi := &file_proto_dininghalls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHalls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHalls) ProtoMessage() {}

func (x *DiningHalls) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHalls.ProtoReflect.Descriptor instead.
func (*DiningHalls) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{0}
}

func (x *DiningHalls) GetDiningHalls() []*DiningHall {
	if x != nil {
		return x.DiningHalls
	}
	return nil
}

type DiningHall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Campus        string                 `protobuf:"bytes,2,opt,name=campus,proto3" json:"campus,omitempty"`
	Building      *DiningHall_Building   `protobuf:"bytes,3,opt,name=building,proto3" json:"building,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Capacity      *DiningHall_Capacity   `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SortPosition  uint32                 `protobuf:"varint,6,opt,name=sortPosition,proto3" json:"sortPosition,omitempty"`
	DayHours      []*DiningHall_DayHour  `protobuf:"bytes,7,rep,name=dayHours,proto3" json:"dayHours,omitempty"`
	DayEvents     []*DiningHall_DayEvent `protobuf:"bytes,8,rep,name=dayEvents,proto3" json:"dayEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHall) Reset() {
	*x = DiningHall{}
	mi := &file_proto_dininghalls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall) ProtoMessage() {}

func (x *DiningHall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall.ProtoReflect.Descriptor instead.
func (*DiningHall) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1}
}

func (x *DiningHall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiningHall) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *DiningHall) GetBuilding() *DiningHall_Building {
	if x != nil {
		return x.Building
	}
	return nil
}

func (x *DiningHall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiningHall) GetCapacity() *DiningHall_Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *DiningHall) GetSortPosition() uint32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *DiningHall) GetDayHours() []*DiningHall_DayHour {
	if x != nil {
		return x.DayHours
	}
	return nil
}

func (x *DiningHall) GetDayEvents() []*DiningHall_DayEvent {
	if x != nil {
		return x.DayEvents
	}
	return nil
}

type DiningHall_Building struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       *DiningHall_Building_Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHall_Building) Reset() {
	*x = DiningHall_Building{}
	mi := &file_proto_dininghalls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_Building) ProtoMessage() {}

func (x *DiningHall_Building) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_Building.ProtoReflect.Descriptor instead.
func (*DiningHall_Building) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DiningHall_Building) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiningHall_Building) GetAddress() *DiningHall_Building_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type DiningHall_Capacity struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CurrentOccupancy      uint32                 `protobuf:"varint,1,opt,name=currentOccupancy,proto3" json:"currentOccupancy,omitempty"`
	CurrentOccupancyRatio uint32                 `protobuf:"varint,2,opt,name=currentOccupancyRatio,proto3" json:"currentOccupancyRatio,omitempty"`
	TotalCapacity         uint32                 `protobuf:"varint,3,opt,name=totalCapacity,proto3" json:"totalCapacity,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DiningHall_Capacity) Reset() {
	*x = DiningHall_Capacity{}
	mi := &file_proto_dininghalls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_Capacity) ProtoMessage() {}

func (x *DiningHall_Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_Capacity.ProtoReflect.Descriptor instead.
func (*DiningHall_Capacity) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DiningHall_Capacity) GetCurrentOccupancy() uint32 {
	if x != nil {
		return x.CurrentOccupancy
	}
	return 0
}

func (x *DiningHall_Capacity) GetCurrentOccupancyRatio() uint32 {
	if x != nil {
		return x.CurrentOccupancyRatio
	}
	return 0
}

func (x *DiningHall_Capacity) GetTotalCapacity() uint32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

type DiningHall_DayHour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Hour          []string               `protobuf:"bytes,2,rep,name=hour,proto3" json:"hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHall_DayHour) Reset() {
	*x = DiningHall_DayHour{}
	mi := &file_proto_dininghalls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_DayHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_DayHour) ProtoMessage() {}

func (x *DiningHall_DayHour) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_DayHour.ProtoReflect.Descriptor instead.
func (*DiningHall_DayHour) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DiningHall_DayHour) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DiningHall_DayHour) GetHour() []string {
	if x != nil {
		return x.Hour
	}
	return nil
}

type DiningHall_DayEvent struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Key           string                               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CalendarEvent []*DiningHall_DayEvent_CalendarEvent `protobuf:"bytes,2,rep,name=calendarEvent,proto3" json:"calendarEvent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHall_DayEvent) Reset() {
	*x = DiningHall_DayEvent{}
	mi := &file_proto_dininghalls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_DayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_DayEvent) ProtoMessage() {}

func (x *DiningHall_DayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_DayEvent.ProtoReflect.Descriptor instead.
func (*DiningHall_DayEvent) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 3}
}

func (x *DiningHall_DayEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DiningHall_DayEvent) GetCalendarEvent() []*DiningHall_DayEvent_CalendarEvent {
	if x != nil {
		return x.CalendarEvent
	}
	return nil
}

type DiningHall_Building_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    uint32                 `protobuf:"varint,2,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Street1       string                 `protobuf:"bytes,4,opt,name=street1,proto3" json:"street1,omitempty"`
	Street2       string                 `protobuf:"bytes,5,opt,name=street2,proto3" json:"street2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHall_Building_Address) Reset() {
	*x = DiningHall_Building_Address{}
	mi := &file_proto_dininghalls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_Building_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_Building_Address) ProtoMessage() {}

func (x *DiningHall_Building_Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_Building_Address.ProtoReflect.Descriptor instead.
func (*DiningHall_Building_Address) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *DiningHall_Building_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DiningHall_Building_Address) GetPostalCode() uint32 {
	if x != nil {
		return x.PostalCode
	}
	return 0
}

func (x *DiningHall_Building_Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DiningHall_Building_Address) GetStreet1() string {
	if x != nil {
		return x.Street1
	}
	return ""
}

func (x *DiningHall_Building_Address) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

type DiningHall_DayEvent_CalendarEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventDayEnd      string                 `protobuf:"bytes,1,opt,name=eventDayEnd,proto3" json:"eventDayEnd,omitempty"`
	EventDayStart    string                 `protobuf:"bytes,2,opt,name=eventDayStart,proto3" json:"eventDayStart,omitempty"`
	EventDescription string                 `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	EventMapLink     string                 `protobuf:"bytes,4,opt,name=eventMapLink,proto3" json:"eventMapLink,omitempty"`
	EventTimeStart   string                 `protobuf:"bytes,5,opt,name=eventTimeStart,proto3" json:"eventTimeStart,omitempty"`
	EventTimeEnd     string                 `protobuf:"bytes,6,opt,name=eventTimeEnd,proto3" json:"eventTimeEnd,omitempty"`
	EventTitle       string                 `protobuf:"bytes,7,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiningHall_DayEvent_CalendarEvent) Reset() {
	*x = DiningHall_DayEvent_CalendarEvent{}
	mi := &file_proto_dininghalls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHall_DayEvent_CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHall_DayEvent_CalendarEvent) ProtoMessage() {}

func (x *DiningHall_DayEvent_CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dininghalls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHall_DayEvent_CalendarEvent.ProtoReflect.Descriptor instead.
func (*DiningHall_DayEvent_CalendarEvent) Descriptor() ([]byte, []int) {
	return file_proto_dininghalls_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventDayEnd() string {
	if x != nil {
		return x.EventDayEnd
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventDayStart() string {
	if x != nil {
		return x.EventDayStart
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventMapLink() string {
	if x != nil {
		return x.EventMapLink
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventTimeStart() string {
	if x != nil {
		return x.EventTimeStart
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventTimeEnd() string {
	if x != nil {
		return x.EventTimeEnd
	}
	return ""
}

func (x *DiningHall_DayEvent_CalendarEvent) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

var File_proto_dininghalls_proto protoreflect.FileDescriptor

const file_proto_dininghalls_proto_rawDesc = "" +
	"\n" +
	"\x17proto/dininghalls.proto\x12\amdining\"D\n" +
	"\vDiningHalls\x125\n" +
	"\vdiningHalls\x18\x01 \x03(\v2\x13.mdining.DiningHallR\vdiningHalls\"\x91\t\n" +
	"\n" +
	"DiningHall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06campus\x18\x02 \x01(\tR\x06campus\x128\n" +
	"\bbuilding\x18\x03 \x01(\v2\x1c.mdining.DiningHall.BuildingR\bbuilding\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x128\n" +
	"\bcapacity\x18\x05 \x01(\v2\x1c.mdining.DiningHall.CapacityR\bcapacity\x12\"\n" +
	"\fsortPosition\x18\x06 \x01(\rR\fsortPosition\x127\n" +
	"\bdayHours\x18\a \x03(\v2\x1b.mdining.DiningHall.DayHourR\bdayHours\x12:\n" +
	"\tdayEvents\x18\b \x03(\v2\x1c.mdining.DiningHall.DayEventR\tdayEvents\x1a\xe8\x01\n" +
	"\bBuilding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\aaddress\x18\x02 \x01(\v2$.mdining.DiningHall.Building.AddressR\aaddress\x1a\x87\x01\n" +
	"\aAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x02 \x01(\rR\n" +
	"postalCode\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\astreet1\x18\x04 \x01(\tR\astreet1\x12\x18\n" +
	"\astreet2\x18\x05 \x01(\tR\astreet2\x1a\x92\x01\n" +
	"\bCapacity\x12*\n" +
	"\x10currentOccupancy\x18\x01 \x01(\rR\x10currentOccupancy\x124\n" +
	"\x15currentOccupancyRatio\x18\x02 \x01(\rR\x15currentOccupancyRatio\x12$\n" +
	"\rtotalCapacity\x18\x03 \x01(\rR\rtotalCapacity\x1a/\n" +
	"\aDayHour\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04hour\x18\x02 \x03(\tR\x04hour\x1a\x84\x03\n" +
	"\bDayEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\rcalendarEvent\x18\x02 \x03(\v2*.mdining.DiningHall.DayEvent.CalendarEventR\rcalendarEvent\x1a\x93\x02\n" +
	"\rCalendarEvent\x12 \n" +
	"\veventDayEnd\x18\x01 \x01(\tR\veventDayEnd\x12$\n" +
	"\reventDayStart\x18\x02 \x01(\tR\reventDayStart\x12*\n" +
	"\x10eventDescription\x18\x03 \x01(\tR\x10eventDescription\x12\"\n" +
	"\feventMapLink\x18\x04 \x01(\tR\feventMapLink\x12&\n" +
	"\x0eeventTimeStart\x18\x05 \x01(\tR\x0eeventTimeStart\x12\"\n" +
	"\feventTimeEnd\x18\x06 \x01(\tR\feventTimeEnd\x12\x1e\n" +
	"\n" +
	"eventTitle\x18\a \x01(\tR\n" +
	"eventTitleb\x06proto3"

var (
	file_proto_dininghalls_proto_rawDescOnce sync.Once
	file_proto_dininghalls_proto_rawDescData []byte
)

func file_proto_dininghalls_proto_rawDescGZIP() []byte {
	file_proto_dininghalls_proto_rawDescOnce.Do(func() {
		file_proto_dininghalls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dininghalls_proto_rawDesc), len(file_proto_dininghalls_proto_rawDesc)))
	})
	return file_proto_dininghalls_proto_rawDescData
}

var file_proto_dininghalls_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_dininghalls_proto_goTypes = []any{
	(*DiningHalls)(nil),                       // 0: mdining.DiningHalls
	(*DiningHall)(nil),                        // 1: mdining.DiningHall
	(*DiningHall_Building)(nil),               // 2: mdining.DiningHall.Building
	(*DiningHall_Capacity)(nil),               // 3: mdining.DiningHall.Capacity
	(*DiningHall_DayHour)(nil),                // 4: mdining.DiningHall.DayHour
	(*DiningHall_DayEvent)(nil),               // 5: mdining.DiningHall.DayEvent
	(*DiningHall_Building_Address)(nil),       // 6: mdining.DiningHall.Building.Address
	(*DiningHall_DayEvent_CalendarEvent)(nil), // 7: mdining.DiningHall.DayEvent.CalendarEvent
}
var file_proto_dininghalls_proto_depIdxs = []int32{
	1, // 0: mdining.DiningHalls.diningHalls:type_name -> mdining.DiningHall
	2, // 1: mdining.DiningHall.building:type_name -> mdining.DiningHall.Building
	3, // 2: mdining.DiningHall.capacity:type_name -> mdining.DiningHall.Capacity
	4, // 3: mdining.DiningHall.dayHours:type_name -> mdining.DiningHall.DayHour
	5, // 4: mdining.DiningHall.dayEvents:type_name -> mdining.DiningHall.DayEvent
	6, // 5: mdining.DiningHall.Building.address:type_name -> mdining.DiningHall.Building.Address
	7, // 6: mdining.DiningHall.DayEvent.calendarEvent:type_name -> mdining.DiningHall.DayEvent.CalendarEvent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_dininghalls_proto_init() }
func file_proto_dininghalls_proto_init() {
	if File_proto_dininghalls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dininghalls_proto_rawDesc), len(file_proto_dininghalls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dininghalls_proto_goTypes,
		DependencyIndexes: file_proto_dininghalls_proto_depIdxs,
		MessageInfos:      file_proto_dininghalls_proto_msgTypes,
	}.Build()
	File_proto_dininghalls_proto = out.File
	file_proto_dininghalls_proto_goTypes = nil
	file_proto_dininghalls_proto_depIdxs = nil
}
