// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/filterableentries.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterableEntries struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FilterableEntries []*FilterableEntry     `protobuf:"bytes,1,rep,name=filterableEntries,proto3" json:"filterableEntries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FilterableEntries) Reset() {
	*x = FilterableEntries{}
	mi := &file_proto_filterableentries_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterableEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterableEntries) ProtoMessage() {}

func (x *FilterableEntries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filterableentries_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterableEntries.ProtoReflect.Descriptor instead.
func (*FilterableEntries) Descriptor() ([]byte, []int) {
	return file_proto_filterableentries_proto_rawDescGZIP(), []int{0}
}

func (x *FilterableEntries) GetFilterableEntries() []*FilterableEntry {
	if x != nil {
		return x.FilterableEntries
	}
	return nil
}

type FilterableEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Attributes     []string               `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Date           string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	DiningHallName string                 `protobuf:"bytes,3,opt,name=diningHallName,proto3" json:"diningHallName,omitempty"`
	ItemName       string                 `protobuf:"bytes,4,opt,name=itemName,proto3" json:"itemName,omitempty"`
	MealNames      []string               `protobuf:"bytes,5,rep,name=mealNames,proto3" json:"mealNames,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilterableEntry) Reset() {
	*x = FilterableEntry{}
	mi := &file_proto_filterableentries_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterableEntry) ProtoMessage() {}

func (x *FilterableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filterableentries_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterableEntry.ProtoReflect.Descriptor instead.
func (*FilterableEntry) Descriptor() ([]byte, []int) {
	return file_proto_filterableentries_proto_rawDescGZIP(), []int{1}
}

func (x *FilterableEntry) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *FilterableEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FilterableEntry) GetDiningHallName() string {
	if x != nil {
		return x.DiningHallName
	}
	return ""
}

func (x *FilterableEntry) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *FilterableEntry) GetMealNames() []string {
	if x != nil {
		return x.MealNames
	}
	return nil
}

var File_proto_filterableentries_proto protoreflect.FileDescriptor

const file_proto_filterableentries_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/filterableentries.proto\x12\amdining\"[\n" +
	"\x11FilterableEntries\x12F\n" +
	"\x11filterableEntries\x18\x01 \x03(\v2\x18.mdining.FilterableEntryR\x11filterableEntries\"\xa7\x01\n" +
	"\x0fFilterableEntry\x12\x1e\n" +
	"\n" +
	"attributes\x18\x01 \x03(\tR\n" +
	"attributes\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12&\n" +
	"\x0ediningHallName\x18\x03 \x01(\tR\x0ediningHallName\x12\x1a\n" +
	"\bitemName\x18\x04 \x01(\tR\bitemName\x12\x1c\n" +
	"\tmealNames\x18\x05 \x03(\tR\tmealNamesb\x06proto3"

var (
	file_proto_filterableentries_proto_rawDescOnce sync.Once
	file_proto_filterableentries_proto_rawDescData []byte
)

func file_proto_filterableentries_proto_rawDescGZIP() []byte {
	file_proto_filterableentries_proto_rawDescOnce.Do(func() {
		file_proto_filterableentries_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filterableentries_proto_rawDesc), len(file_proto_filterableentries_proto_rawDesc)))
	})
	return file_proto_filterableentries_proto_rawDescData
}

var file_proto_filterableentries_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_filterableentries_proto_goTypes = []any{
	(*FilterableEntries)(nil), // 0: mdining.FilterableEntries
	(*FilterableEntry)(nil),   // 1: mdining.FilterableEntry
}
var file_proto_filterableentries_proto_depIdxs = []int32{
	1, // 0: mdining.FilterableEntries.filterableEntries:type_name -> mdining.FilterableEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_filterableentries_proto_init() }
func file_proto_filterableentries_proto_init() {
	if File_proto_filterableentries_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filterableentries_proto_rawDesc), len(file_proto_filterableentries_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_filterableentries_proto_goTypes,
		DependencyIndexes: file_proto_filterableentries_proto_depIdxs,
		MessageInfos:      file_proto_filterableentries_proto_msgTypes,
	}.Build()
	File_proto_filterableentries_proto = out.File
	file_proto_filterableentries_proto_goTypes = nil
	file_proto_filterableentries_proto_depIdxs = nil
}
