// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/food.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Food struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	Key             string                          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Date            string                          `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Name            string                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category        []string                        `protobuf:"bytes,4,rep,name=category,proto3" json:"category,omitempty"`
	MenuItem        *MenuItem                       `protobuf:"bytes,5,opt,name=menuItem,proto3" json:"menuItem,omitempty"`
	DiningHallMatch map[string]*FoodDiningHallMatch `protobuf:"bytes,6,rep,name=diningHallMatch,proto3" json:"diningHallMatch,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Food) Reset() {
	*x = Food{}
	mi := &file_proto_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Food) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Food) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Food) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Food) GetMenuItem() *MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

func (x *Food) GetDiningHallMatch() map[string]*FoodDiningHallMatch {
	if x != nil {
		return x.DiningHallMatch
	}
	return nil
}

type FoodDiningHallMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MealTime      map[string]*MealTime   `protobuf:"bytes,2,rep,name=mealTime,proto3" json:"mealTime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Campus        string                 `protobuf:"bytes,3,opt,name=campus,proto3" json:"campus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodDiningHallMatch) Reset() {
	*x = FoodDiningHallMatch{}
	mi := &file_proto_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodDiningHallMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodDiningHallMatch) ProtoMessage() {}

func (x *FoodDiningHallMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodDiningHallMatch.ProtoReflect.Descriptor instead.
func (*FoodDiningHallMatch) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodDiningHallMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodDiningHallMatch) GetMealTime() map[string]*MealTime {
	if x != nil {
		return x.MealTime
	}
	return nil
}

func (x *FoodDiningHallMatch) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

type MealTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	FormattedDate string                 `protobuf:"bytes,2,opt,name=formattedDate,proto3" json:"formattedDate,omitempty"`
	MealNames     []string               `protobuf:"bytes,3,rep,name=mealNames,proto3" json:"mealNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealTime) Reset() {
	*x = MealTime{}
	mi := &file_proto_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealTime) ProtoMessage() {}

func (x *MealTime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealTime.ProtoReflect.Descriptor instead.
func (*MealTime) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{2}
}

func (x *MealTime) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MealTime) GetFormattedDate() string {
	if x != nil {
		return x.FormattedDate
	}
	return ""
}

func (x *MealTime) GetMealNames() []string {
	if x != nil {
		return x.MealNames
	}
	return nil
}

var File_proto_food_proto protoreflect.FileDescriptor

const file_proto_food_proto_rawDesc = "" +
	"\n" +
	"\x10proto/food.proto\x12\amdining\x1a\x10proto/menu.proto\"\xbb\x02\n" +
	"\x04Food\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x03(\tR\bcategory\x12-\n" +
	"\bmenuItem\x18\x05 \x01(\v2\x11.mdining.MenuItemR\bmenuItem\x12L\n" +
	"\x0fdiningHallMatch\x18\x06 \x03(\v2\".mdining.Food.DiningHallMatchEntryR\x0fdiningHallMatch\x1a`\n" +
	"\x14DiningHallMatchEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.mdining.FoodDiningHallMatchR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x13FoodDiningHallMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bmealTime\x18\x02 \x03(\v2*.mdining.FoodDiningHallMatch.MealTimeEntryR\bmealTime\x12\x16\n" +
	"\x06campus\x18\x03 \x01(\tR\x06campus\x1aN\n" +
	"\rMealTimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.mdining.MealTimeR\x05value:\x028\x01\"b\n" +
	"\bMealTime\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12$\n" +
	"\rformattedDate\x18\x02 \x01(\tR\rformattedDate\x12\x1c\n" +
	"\tmealNames\x18\x03 \x03(\tR\tmealNamesb\x06proto3"

var (
	file_proto_food_proto_rawDescOnce sync.Once
	file_proto_food_proto_rawDescData []byte
)

func file_proto_food_proto_rawDescGZIP() []byte {
	file_proto_food_proto_rawDescOnce.Do(func() {
		file_proto_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)))
	})
	return file_proto_food_proto_rawDescData
}

var file_proto_food_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_food_proto_goTypes = []any{
	(*Food)(nil),                // 0: mdining.Food
	(*FoodDiningHallMatch)(nil), // 1: mdining.FoodDiningHallMatch
	(*MealTime)(nil),            // 2: mdining.MealTime
	nil,                         // 3: mdining.Food.DiningHallMatchEntry
	nil,                         // 4: mdining.FoodDiningHallMatch.MealTimeEntry
	(*MenuItem)(nil),            // 5: mdining.MenuItem
}
var file_proto_food_proto_depIdxs = []int32{
	5, // 0: mdining.Food.menuItem:type_name -> mdining.MenuItem
	3, // 1: mdining.Food.diningHallMatch:type_name -> mdining.Food.DiningHallMatchEntry
	4, // 2: mdining.FoodDiningHallMatch.mealTime:type_name -> mdining.FoodDiningHallMatch.MealTimeEntry
	1, // 3: mdining.Food.DiningHallMatchEntry.value:type_name -> mdining.FoodDiningHallMatch
	2, // 4: mdining.FoodDiningHallMatch.MealTimeEntry.value:type_name -> mdining.MealTime
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_food_proto_init() }
func file_proto_food_proto_init() {
	if File_proto_food_proto != nil {
		return
	}
	file_proto_menu_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_food_proto_goTypes,
		DependencyIndexes: file_proto_food_proto_depIdxs,
		MessageInfos:      file_proto_food_proto_msgTypes,
	}.Build()
	File_proto_food_proto = out.File
	file_proto_food_proto_goTypes = nil
	file_proto_food_proto_depIdxs = nil
}
