// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/foodstat.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodStat struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Date                  string                  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TimesServed           map[string]int64        `protobuf:"bytes,2,rep,name=timesServed,proto3" json:"timesServed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FoodDiningHallCounts  map[string]*StringToInt `protobuf:"bytes,3,rep,name=foodDiningHallCounts,proto3" json:"foodDiningHallCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DiningHallFoodCounts  map[string]*StringToInt `protobuf:"bytes,4,rep,name=diningHallFoodCounts,proto3" json:"diningHallFoodCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CategoryCounts        map[string]int64        `protobuf:"bytes,5,rep,name=categoryCounts,proto3" json:"categoryCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AllergenCounts        map[string]int64        `protobuf:"bytes,6,rep,name=allergenCounts,proto3" json:"allergenCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AttributeCounts       map[string]int64        `protobuf:"bytes,7,rep,name=attributeCounts,proto3" json:"attributeCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	WeekdayFoodCounts     map[string]*StringToInt `protobuf:"bytes,8,rep,name=weekdayFoodCounts,proto3" json:"weekdayFoodCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FoodWeekdayCounts     map[string]*StringToInt `protobuf:"bytes,9,rep,name=foodWeekdayCounts,proto3" json:"foodWeekdayCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NumUniqueFoods        int64                   `protobuf:"varint,10,opt,name=numUniqueFoods,proto3" json:"numUniqueFoods,omitempty"`
	TotalFoodMealsServed  int64                   `protobuf:"varint,11,opt,name=totalFoodMealsServed,proto3" json:"totalFoodMealsServed,omitempty"`
	DiningHallMealsServed map[string]int64        `protobuf:"bytes,12,rep,name=diningHallMealsServed,proto3" json:"diningHallMealsServed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FoodStat) Reset() {
	*x = FoodStat{}
	mi := &file_proto_foodstat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStat) ProtoMessage() {}

func (x *FoodStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foodstat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStat.ProtoReflect.Descriptor instead.
func (*FoodStat) Descriptor() ([]byte, []int) {
	return file_proto_foodstat_proto_rawDescGZIP(), []int{0}
}

func (x *FoodStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FoodStat) GetTimesServed() map[string]int64 {
	if x != nil {
		return x.TimesServed
	}
	return nil
}

func (x *FoodStat) GetFoodDiningHallCounts() map[string]*StringToInt {
	if x != nil {
		return x.FoodDiningHallCounts
	}
	return nil
}

func (x *FoodStat) GetDiningHallFoodCounts() map[string]*StringToInt {
	if x != nil {
		return x.DiningHallFoodCounts
	}
	return nil
}

func (x *FoodStat) GetCategoryCounts() map[string]int64 {
	if x != nil {
		return x.CategoryCounts
	}
	return nil
}

func (x *FoodStat) GetAllergenCounts() map[string]int64 {
	if x != nil {
		return x.AllergenCounts
	}
	return nil
}

func (x *FoodStat) GetAttributeCounts() map[string]int64 {
	if x != nil {
		return x.AttributeCounts
	}
	return nil
}

func (x *FoodStat) GetWeekdayFoodCounts() map[string]*StringToInt {
	if x != nil {
		return x.WeekdayFoodCounts
	}
	return nil
}

func (x *FoodStat) GetFoodWeekdayCounts() map[string]*StringToInt {
	if x != nil {
		return x.FoodWeekdayCounts
	}
	return nil
}

func (x *FoodStat) GetNumUniqueFoods() int64 {
	if x != nil {
		return x.NumUniqueFoods
	}
	return 0
}

func (x *FoodStat) GetTotalFoodMealsServed() int64 {
	if x != nil {
		return x.TotalFoodMealsServed
	}
	return 0
}

func (x *FoodStat) GetDiningHallMealsServed() map[string]int64 {
	if x != nil {
		return x.DiningHallMealsServed
	}
	return nil
}

type CountArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []int64                `protobuf:"varint,1,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountArray) Reset() {
	*x = CountArray{}
	mi := &file_proto_foodstat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountArray) ProtoMessage() {}

func (x *CountArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foodstat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountArray.ProtoReflect.Descriptor instead.
func (*CountArray) Descriptor() ([]byte, []int) {
	return file_proto_foodstat_proto_rawDescGZIP(), []int{1}
}

func (x *CountArray) GetCounts() []int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type SummaryStats struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Dates                   []string               `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	NumUniqueFoods          []int64                `protobuf:"varint,2,rep,packed,name=numUniqueFoods,proto3" json:"numUniqueFoods,omitempty"`
	TotalFoodMealsServed    []int64                `protobuf:"varint,3,rep,packed,name=totalFoodMealsServed,proto3" json:"totalFoodMealsServed,omitempty"`
	AllergenCounts          map[string]*CountArray `protobuf:"bytes,4,rep,name=allergenCounts,proto3" json:"allergenCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AttributeCounts         map[string]*CountArray `protobuf:"bytes,5,rep,name=attributeCounts,proto3" json:"attributeCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Foods                   []string               `protobuf:"bytes,6,rep,name=foods,proto3" json:"foods,omitempty"`
	LatestWeekdayFoodCounts map[string]*CountArray `protobuf:"bytes,7,rep,name=latestWeekdayFoodCounts,proto3" json:"latestWeekdayFoodCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SummaryStats) Reset() {
	*x = SummaryStats{}
	mi := &file_proto_foodstat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryStats) ProtoMessage() {}

func (x *SummaryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foodstat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryStats.ProtoReflect.Descriptor instead.
func (*SummaryStats) Descriptor() ([]byte, []int) {
	return file_proto_foodstat_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryStats) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *SummaryStats) GetNumUniqueFoods() []int64 {
	if x != nil {
		return x.NumUniqueFoods
	}
	return nil
}

func (x *SummaryStats) GetTotalFoodMealsServed() []int64 {
	if x != nil {
		return x.TotalFoodMealsServed
	}
	return nil
}

func (x *SummaryStats) GetAllergenCounts() map[string]*CountArray {
	if x != nil {
		return x.AllergenCounts
	}
	return nil
}

func (x *SummaryStats) GetAttributeCounts() map[string]*CountArray {
	if x != nil {
		return x.AttributeCounts
	}
	return nil
}

func (x *SummaryStats) GetFoods() []string {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *SummaryStats) GetLatestWeekdayFoodCounts() map[string]*CountArray {
	if x != nil {
		return x.LatestWeekdayFoodCounts
	}
	return nil
}

type StringToInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]int64       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringToInt) Reset() {
	*x = StringToInt{}
	mi := &file_proto_foodstat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringToInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringToInt) ProtoMessage() {}

func (x *StringToInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foodstat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringToInt.ProtoReflect.Descriptor instead.
func (*StringToInt) Descriptor() ([]byte, []int) {
	return file_proto_foodstat_proto_rawDescGZIP(), []int{3}
}

func (x *StringToInt) GetData() map[string]int64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_foodstat_proto protoreflect.FileDescriptor

const file_proto_foodstat_proto_rawDesc = "" +
	"\n" +
	"\x14proto/foodstat.proto\x12\amdining\"\xd0\f\n" +
	"\bFoodStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12D\n" +
	"\vtimesServed\x18\x02 \x03(\v2\".mdining.FoodStat.TimesServedEntryR\vtimesServed\x12_\n" +
	"\x14foodDiningHallCounts\x18\x03 \x03(\v2+.mdining.FoodStat.FoodDiningHallCountsEntryR\x14foodDiningHallCounts\x12_\n" +
	"\x14diningHallFoodCounts\x18\x04 \x03(\v2+.mdining.FoodStat.DiningHallFoodCountsEntryR\x14diningHallFoodCounts\x12M\n" +
	"\x0ecategoryCounts\x18\x05 \x03(\v2%.mdining.FoodStat.CategoryCountsEntryR\x0ecategoryCounts\x12M\n" +
	"\x0eallergenCounts\x18\x06 \x03(\v2%.mdining.FoodStat.AllergenCountsEntryR\x0eallergenCounts\x12P\n" +
	"\x0fattributeCounts\x18\a \x03(\v2&.mdining.FoodStat.AttributeCountsEntryR\x0fattributeCounts\x12V\n" +
	"\x11weekdayFoodCounts\x18\b \x03(\v2(.mdining.FoodStat.WeekdayFoodCountsEntryR\x11weekdayFoodCounts\x12V\n" +
	"\x11foodWeekdayCounts\x18\t \x03(\v2(.mdining.FoodStat.FoodWeekdayCountsEntryR\x11foodWeekdayCounts\x12&\n" +
	"\x0enumUniqueFoods\x18\n" +
	" \x01(\x03R\x0enumUniqueFoods\x122\n" +
	"\x14totalFoodMealsServed\x18\v \x01(\x03R\x14totalFoodMealsServed\x12b\n" +
	"\x15diningHallMealsServed\x18\f \x03(\v2,.mdining.FoodStat.DiningHallMealsServedEntryR\x15diningHallMealsServed\x1a>\n" +
	"\x10TimesServedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a]\n" +
	"\x19FoodDiningHallCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mdining.StringToIntR\x05value:\x028\x01\x1a]\n" +
	"\x19DiningHallFoodCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mdining.StringToIntR\x05value:\x028\x01\x1aA\n" +
	"\x13CategoryCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aA\n" +
	"\x13AllergenCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14AttributeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aZ\n" +
	"\x16WeekdayFoodCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mdining.StringToIntR\x05value:\x028\x01\x1aZ\n" +
	"\x16FoodWeekdayCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mdining.StringToIntR\x05value:\x028\x01\x1aH\n" +
	"\x1aDiningHallMealsServedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"$\n" +
	"\n" +
	"CountArray\x12\x16\n" +
	"\x06counts\x18\x01 \x03(\x03R\x06counts\"\xbf\x05\n" +
	"\fSummaryStats\x12\x14\n" +
	"\x05dates\x18\x01 \x03(\tR\x05dates\x12&\n" +
	"\x0enumUniqueFoods\x18\x02 \x03(\x03R\x0enumUniqueFoods\x122\n" +
	"\x14totalFoodMealsServed\x18\x03 \x03(\x03R\x14totalFoodMealsServed\x12Q\n" +
	"\x0eallergenCounts\x18\x04 \x03(\v2).mdining.SummaryStats.AllergenCountsEntryR\x0eallergenCounts\x12T\n" +
	"\x0fattributeCounts\x18\x05 \x03(\v2*.mdining.SummaryStats.AttributeCountsEntryR\x0fattributeCounts\x12\x14\n" +
	"\x05foods\x18\x06 \x03(\tR\x05foods\x12l\n" +
	"\x17latestWeekdayFoodCounts\x18\a \x03(\v22.mdining.SummaryStats.LatestWeekdayFoodCountsEntryR\x17latestWeekdayFoodCounts\x1aV\n" +
	"\x13AllergenCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mdining.CountArrayR\x05value:\x028\x01\x1aW\n" +
	"\x14AttributeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mdining.CountArrayR\x05value:\x028\x01\x1a_\n" +
	"\x1cLatestWeekdayFoodCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mdining.CountArrayR\x05value:\x028\x01\"z\n" +
	"\vStringToInt\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.mdining.StringToInt.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01b\x06proto3"

var (
	file_proto_foodstat_proto_rawDescOnce sync.Once
	file_proto_foodstat_proto_rawDescData []byte
)

func file_proto_foodstat_proto_rawDescGZIP() []byte {
	file_proto_foodstat_proto_rawDescOnce.Do(func() {
		file_proto_foodstat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_foodstat_proto_rawDesc), len(file_proto_foodstat_proto_rawDesc)))
	})
	return file_proto_foodstat_proto_rawDescData
}

var file_proto_foodstat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_foodstat_proto_goTypes = []any{
	(*FoodStat)(nil),     // 0: mdining.FoodStat
	(*CountArray)(nil),   // 1: mdining.CountArray
	(*SummaryStats)(nil), // 2: mdining.SummaryStats
	(*StringToInt)(nil),  // 3: mdining.StringToInt
	nil,                  // 4: mdining.FoodStat.TimesServedEntry
	nil,                  // 5: mdining.FoodStat.FoodDiningHallCountsEntry
	nil,                  // 6: mdining.FoodStat.DiningHallFoodCountsEntry
	nil,                  // 7: mdining.FoodStat.CategoryCountsEntry
	nil,                  // 8: mdining.FoodStat.AllergenCountsEntry
	nil,                  // 9: mdining.FoodStat.AttributeCountsEntry
	nil,                  // 10: mdining.FoodStat.WeekdayFoodCountsEntry
	nil,                  // 11: mdining.FoodStat.FoodWeekdayCountsEntry
	nil,                  // 12: mdining.FoodStat.DiningHallMealsServedEntry
	nil,                  // 13: mdining.SummaryStats.AllergenCountsEntry
	nil,                  // 14: mdining.SummaryStats.AttributeCountsEntry
	nil,                  // 15: mdining.SummaryStats.LatestWeekdayFoodCountsEntry
	nil,                  // 16: mdining.StringToInt.DataEntry
}
var file_proto_foodstat_proto_depIdxs = []int32{
	4,  // 0: mdining.FoodStat.timesServed:type_name -> mdining.FoodStat.TimesServedEntry
	5,  // 1: mdining.FoodStat.foodDiningHallCounts:type_name -> mdining.FoodStat.FoodDiningHallCountsEntry
	6,  // 2: mdining.FoodStat.diningHallFoodCounts:type_name -> mdining.FoodStat.DiningHallFoodCountsEntry
	7,  // 3: mdining.FoodStat.categoryCounts:type_name -> mdining.FoodStat.CategoryCountsEntry
	8,  // 4: mdining.FoodStat.allergenCounts:type_name -> mdining.FoodStat.AllergenCountsEntry
	9,  // 5: mdining.FoodStat.attributeCounts:type_name -> mdining.FoodStat.AttributeCountsEntry
	10, // 6: mdining.FoodStat.weekdayFoodCounts:type_name -> mdining.FoodStat.WeekdayFoodCountsEntry
	11, // 7: mdining.FoodStat.foodWeekdayCounts:type_name -> mdining.FoodStat.FoodWeekdayCountsEntry
	12, // 8: mdining.FoodStat.diningHallMealsServed:type_name -> mdining.FoodStat.DiningHallMealsServedEntry
	13, // 9: mdining.SummaryStats.allergenCounts:type_name -> mdining.SummaryStats.AllergenCountsEntry
	14, // 10: mdining.SummaryStats.attributeCounts:type_name -> mdining.SummaryStats.AttributeCountsEntry
	15, // 11: mdining.SummaryStats.latestWeekdayFoodCounts:type_name -> mdining.SummaryStats.LatestWeekdayFoodCountsEntry
	16, // 12: mdining.StringToInt.data:type_name -> mdining.StringToInt.DataEntry
	3,  // 13: mdining.FoodStat.FoodDiningHallCountsEntry.value:type_name -> mdining.StringToInt
	3,  // 14: mdining.FoodStat.DiningHallFoodCountsEntry.value:type_name -> mdining.StringToInt
	3,  // 15: mdining.FoodStat.WeekdayFoodCountsEntry.value:type_name -> mdining.StringToInt
	3,  // 16: mdining.FoodStat.FoodWeekdayCountsEntry.value:type_name -> mdining.StringToInt
	1,  // 17: mdining.SummaryStats.AllergenCountsEntry.value:type_name -> mdining.CountArray
	1,  // 18: mdining.SummaryStats.AttributeCountsEntry.value:type_name -> mdining.CountArray
	1,  // 19: mdining.SummaryStats.LatestWeekdayFoodCountsEntry.value:type_name -> mdining.CountArray
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_foodstat_proto_init() }
func file_proto_foodstat_proto_init() {
	if File_proto_foodstat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_foodstat_proto_rawDesc), len(file_proto_foodstat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_foodstat_proto_goTypes,
		DependencyIndexes: file_proto_foodstat_proto_depIdxs,
		MessageInfos:      file_proto_foodstat_proto_msgTypes,
	}.Build()
	File_proto_foodstat_proto = out.File
	file_proto_foodstat_proto_goTypes = nil
	file_proto_foodstat_proto_depIdxs = nil
}
