// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/items.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*Item       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_proto_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{0}
}

func (x *Items) GetItems() map[string]*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	Name                   string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attributes             []string                         `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DiningHallMatches      map[string]*Item_DiningHallMatch `protobuf:"bytes,3,rep,name=diningHallMatches,proto3" json:"diningHallMatches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DiningHallMatchesArray []*Item_DiningHallMatch          `protobuf:"bytes,4,rep,name=diningHallMatchesArray,proto3" json:"diningHallMatchesArray,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Item) GetDiningHallMatches() map[string]*Item_DiningHallMatch {
	if x != nil {
		return x.DiningHallMatches
	}
	return nil
}

func (x *Item) GetDiningHallMatchesArray() []*Item_DiningHallMatch {
	if x != nil {
		return x.DiningHallMatchesArray
	}
	return nil
}

type Item_DiningHallMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MealTimes      map[string]*MealTime   `protobuf:"bytes,2,rep,name=mealTimes,proto3" json:"mealTimes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MealTimesArray []*MealTime            `protobuf:"bytes,3,rep,name=mealTimesArray,proto3" json:"mealTimesArray,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Item_DiningHallMatch) Reset() {
	*x = Item_DiningHallMatch{}
	mi := &file_proto_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item_DiningHallMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item_DiningHallMatch) ProtoMessage() {}

func (x *Item_DiningHallMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item_DiningHallMatch.ProtoReflect.Descriptor instead.
func (*Item_DiningHallMatch) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Item_DiningHallMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item_DiningHallMatch) GetMealTimes() map[string]*MealTime {
	if x != nil {
		return x.MealTimes
	}
	return nil
}

func (x *Item_DiningHallMatch) GetMealTimesArray() []*MealTime {
	if x != nil {
		return x.MealTimesArray
	}
	return nil
}

var File_proto_items_proto protoreflect.FileDescriptor

const file_proto_items_proto_rawDesc = "" +
	"\n" +
	"\x11proto/items.proto\x12\amdining\x1a\x10proto/food.proto\"\x81\x01\n" +
	"\x05Items\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.mdining.Items.ItemsEntryR\x05items\x1aG\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.mdining.ItemR\x05value:\x028\x01\"\xca\x04\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x03(\tR\n" +
	"attributes\x12R\n" +
	"\x11diningHallMatches\x18\x03 \x03(\v2$.mdining.Item.DiningHallMatchesEntryR\x11diningHallMatches\x12U\n" +
	"\x16diningHallMatchesArray\x18\x04 \x03(\v2\x1d.mdining.Item.DiningHallMatchR\x16diningHallMatchesArray\x1ac\n" +
	"\x16DiningHallMatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.mdining.Item.DiningHallMatchR\x05value:\x028\x01\x1a\xfd\x01\n" +
	"\x0fDiningHallMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\tmealTimes\x18\x02 \x03(\v2,.mdining.Item.DiningHallMatch.MealTimesEntryR\tmealTimes\x129\n" +
	"\x0emealTimesArray\x18\x03 \x03(\v2\x11.mdining.MealTimeR\x0emealTimesArray\x1aO\n" +
	"\x0eMealTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.mdining.MealTimeR\x05value:\x028\x01b\x06proto3"

var (
	file_proto_items_proto_rawDescOnce sync.Once
	file_proto_items_proto_rawDescData []byte
)

func file_proto_items_proto_rawDescGZIP() []byte {
	file_proto_items_proto_rawDescOnce.Do(func() {
		file_proto_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)))
	})
	return file_proto_items_proto_rawDescData
}

var file_proto_items_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_items_proto_goTypes = []any{
	(*Items)(nil),                // 0: mdining.Items
	(*Item)(nil),                 // 1: mdining.Item
	nil,                          // 2: mdining.Items.ItemsEntry
	nil,                          // 3: mdining.Item.DiningHallMatchesEntry
	(*Item_DiningHallMatch)(nil), // 4: mdining.Item.DiningHallMatch
	nil,                          // 5: mdining.Item.DiningHallMatch.MealTimesEntry
	(*MealTime)(nil),             // 6: mdining.MealTime
}
var file_proto_items_proto_depIdxs = []int32{
	2, // 0: mdining.Items.items:type_name -> mdining.Items.ItemsEntry
	3, // 1: mdining.Item.diningHallMatches:type_name -> mdining.Item.DiningHallMatchesEntry
	4, // 2: mdining.Item.diningHallMatchesArray:type_name -> mdining.Item.DiningHallMatch
	1, // 3: mdining.Items.ItemsEntry.value:type_name -> mdining.Item
	4, // 4: mdining.Item.DiningHallMatchesEntry.value:type_name -> mdining.Item.DiningHallMatch
	5, // 5: mdining.Item.DiningHallMatch.mealTimes:type_name -> mdining.Item.DiningHallMatch.MealTimesEntry
	6, // 6: mdining.Item.DiningHallMatch.mealTimesArray:type_name -> mdining.MealTime
	6, // 7: mdining.Item.DiningHallMatch.MealTimesEntry.value:type_name -> mdining.MealTime
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_items_proto_init() }
func file_proto_items_proto_init() {
	if File_proto_items_proto != nil {
		return
	}
	file_proto_food_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_items_proto_goTypes,
		DependencyIndexes: file_proto_items_proto_depIdxs,
		MessageInfos:      file_proto_items_proto_msgTypes,
	}.Build()
	File_proto_items_proto = out.File
	file_proto_items_proto_goTypes = nil
	file_proto_items_proto_depIdxs = nil
}
