// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/mdining.proto

package mdining

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodStatsRequest) Reset() {
	*x = FoodStatsRequest{}
	mi := &file_proto_mdining_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStatsRequest) ProtoMessage() {}

func (x *FoodStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStatsRequest.ProtoReflect.Descriptor instead.
func (*FoodStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{0}
}

type FoodStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodStats     []*FoodStat            `protobuf:"bytes,1,rep,name=foodStats,proto3" json:"foodStats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodStatsReply) Reset() {
	*x = FoodStatsReply{}
	mi := &file_proto_mdining_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStatsReply) ProtoMessage() {}

func (x *FoodStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStatsReply.ProtoReflect.Descriptor instead.
func (*FoodStatsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{1}
}

func (x *FoodStatsReply) GetFoodStats() []*FoodStat {
	if x != nil {
		return x.FoodStats
	}
	return nil
}

type SummaryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryStatsRequest) Reset() {
	*x = SummaryStatsRequest{}
	mi := &file_proto_mdining_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryStatsRequest) ProtoMessage() {}

func (x *SummaryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryStatsRequest.ProtoReflect.Descriptor instead.
func (*SummaryStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SummaryStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type SummaryStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *SummaryStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryStatsReply) Reset() {
	*x = SummaryStatsReply{}
	mi := &file_proto_mdining_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryStatsReply) ProtoMessage() {}

func (x *SummaryStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryStatsReply.ProtoReflect.Descriptor instead.
func (*SummaryStatsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryStatsReply) GetStats() *SummaryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DiningHallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHallsRequest) Reset() {
	*x = DiningHallsRequest{}
	mi := &file_proto_mdining_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHallsRequest) ProtoMessage() {}

func (x *DiningHallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHallsRequest.ProtoReflect.Descriptor instead.
func (*DiningHallsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{4}
}

type DiningHallsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiningHalls   []*DiningHall          `protobuf:"bytes,1,rep,name=diningHalls,proto3" json:"diningHalls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiningHallsReply) Reset() {
	*x = DiningHallsReply{}
	mi := &file_proto_mdining_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiningHallsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiningHallsReply) ProtoMessage() {}

func (x *DiningHallsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiningHallsReply.ProtoReflect.Descriptor instead.
func (*DiningHallsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{5}
}

func (x *DiningHallsReply) GetDiningHalls() []*DiningHall {
	if x != nil {
		return x.DiningHalls
	}
	return nil
}

type ItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsRequest) Reset() {
	*x = ItemsRequest{}
	mi := &file_proto_mdining_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsRequest) ProtoMessage() {}

func (x *ItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsRequest.ProtoReflect.Descriptor instead.
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{6}
}

type ItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*Item       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsReply) Reset() {
	*x = ItemsReply{}
	mi := &file_proto_mdining_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsReply) ProtoMessage() {}

func (x *ItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsReply.ProtoReflect.Descriptor instead.
func (*ItemsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{7}
}

func (x *ItemsReply) GetItems() map[string]*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type FilterableEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterableEntriesRequest) Reset() {
	*x = FilterableEntriesRequest{}
	mi := &file_proto_mdining_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterableEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterableEntriesRequest) ProtoMessage() {}

func (x *FilterableEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterableEntriesRequest.ProtoReflect.Descriptor instead.
func (*FilterableEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{8}
}

type FilterableEntriesReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FilterableEntries []*FilterableEntry     `protobuf:"bytes,1,rep,name=filterableEntries,proto3" json:"filterableEntries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FilterableEntriesReply) Reset() {
	*x = FilterableEntriesReply{}
	mi := &file_proto_mdining_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterableEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterableEntriesReply) ProtoMessage() {}

func (x *FilterableEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterableEntriesReply.ProtoReflect.Descriptor instead.
func (*FilterableEntriesReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{9}
}

func (x *FilterableEntriesReply) GetFilterableEntries() []*FilterableEntry {
	if x != nil {
		return x.FilterableEntries
	}
	return nil
}

type AllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllRequest) Reset() {
	*x = AllRequest{}
	mi := &file_proto_mdining_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRequest) ProtoMessage() {}

func (x *AllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRequest.ProtoReflect.Descriptor instead.
func (*AllRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{10}
}

type AllReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiningHalls       []*DiningHall          `protobuf:"bytes,1,rep,name=diningHalls,proto3" json:"diningHalls,omitempty"`
	Items             map[string]*Item       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FilterableEntries []*FilterableEntry     `protobuf:"bytes,3,rep,name=filterableEntries,proto3" json:"filterableEntries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AllReply) Reset() {
	*x = AllReply{}
	mi := &file_proto_mdining_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReply) ProtoMessage() {}

func (x *AllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReply.ProtoReflect.Descriptor instead.
func (*AllReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{11}
}

func (x *AllReply) GetDiningHalls() []*DiningHall {
	if x != nil {
		return x.DiningHalls
	}
	return nil
}

func (x *AllReply) GetItems() map[string]*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AllReply) GetFilterableEntries() []*FilterableEntry {
	if x != nil {
		return x.FilterableEntries
	}
	return nil
}

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Meal          string                 `protobuf:"bytes,2,opt,name=meal,proto3" json:"meal,omitempty"`
	DiningHall    string                 `protobuf:"bytes,3,opt,name=diningHall,proto3" json:"diningHall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_proto_mdining_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{12}
}

func (x *MenuRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MenuRequest) GetMeal() string {
	if x != nil {
		return x.Meal
	}
	return ""
}

func (x *MenuRequest) GetDiningHall() string {
	if x != nil {
		return x.DiningHall
	}
	return ""
}

type MenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*Menu                `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuReply) Reset() {
	*x = MenuReply{}
	mi := &file_proto_mdining_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuReply) ProtoMessage() {}

func (x *MenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuReply.ProtoReflect.Descriptor instead.
func (*MenuReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{13}
}

func (x *MenuReply) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type FoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodRequest) Reset() {
	*x = FoodRequest{}
	mi := &file_proto_mdining_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodRequest) ProtoMessage() {}

func (x *FoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodRequest.ProtoReflect.Descriptor instead.
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{14}
}

func (x *FoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FoodRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FoodRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type FoodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foods         []*Food                `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodReply) Reset() {
	*x = FoodReply{}
	mi := &file_proto_mdining_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodReply) ProtoMessage() {}

func (x *FoodReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodReply.ProtoReflect.Descriptor instead.
func (*FoodReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{15}
}

func (x *FoodReply) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

type HeartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartsRequest) Reset() {
	*x = HeartsRequest{}
	mi := &file_proto_mdining_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartsRequest) ProtoMessage() {}

func (x *HeartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartsRequest.ProtoReflect.Descriptor instead.
func (*HeartsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{16}
}

func (x *HeartsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type HeartsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []*HeartCount          `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartsReply) Reset() {
	*x = HeartsReply{}
	mi := &file_proto_mdining_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartsReply) ProtoMessage() {}

func (x *HeartsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdining_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartsReply.ProtoReflect.Descriptor instead.
func (*HeartsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdining_proto_rawDescGZIP(), []int{17}
}

func (x *HeartsReply) GetCounts() []*HeartCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_proto_mdining_proto protoreflect.FileDescriptor

const file_proto_mdining_proto_rawDesc = "" +
	"\n" +
	"\x13proto/mdining.proto\x12\amdining\x1a\x1cgoogle/api/annotations.proto\x1a\x17proto/dininghalls.proto\x1a\x11proto/items.proto\x1a\x1dproto/filterableentries.proto\x1a\x10proto/menu.proto\x1a\x10proto/food.proto\x1a\x14proto/foodstat.proto\x1a\x12proto/hearts.proto\"\x12\n" +
	"\x10FoodStatsRequest\"A\n" +
	"\x0eFoodStatsReply\x12/\n" +
	"\tfoodStats\x18\x01 \x03(\v2\x11.mdining.FoodStatR\tfoodStats\"M\n" +
	"\x13SummaryStatsRequest\x12\x1c\n" +
	"\tstartDate\x18\x01 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x02 \x01(\tR\aendDate\"@\n" +
	"\x11SummaryStatsReply\x12+\n" +
	"\x05stats\x18\x01 \x01(\v2\x15.mdining.SummaryStatsR\x05stats\"\x14\n" +
	"\x12DiningHallsRequest\"I\n" +
	"\x10DiningHallsReply\x125\n" +
	"\vdiningHalls\x18\x01 \x03(\v2\x13.mdining.DiningHallR\vdiningHalls\"\x0e\n" +
	"\fItemsRequest\"\x8b\x01\n" +
	"\n" +
	"ItemsReply\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.mdining.ItemsReply.ItemsEntryR\x05items\x1aG\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.mdining.ItemR\x05value:\x028\x01\"\x1a\n" +
	"\x18FilterableEntriesRequest\"`\n" +
	"\x16FilterableEntriesReply\x12F\n" +
	"\x11filterableEntries\x18\x01 \x03(\v2\x18.mdining.FilterableEntryR\x11filterableEntries\"\f\n" +
	"\n" +
	"AllRequest\"\x86\x02\n" +
	"\bAllReply\x125\n" +
	"\vdiningHalls\x18\x01 \x03(\v2\x13.mdining.DiningHallR\vdiningHalls\x122\n" +
	"\x05items\x18\x02 \x03(\v2\x1c.mdining.AllReply.ItemsEntryR\x05items\x12F\n" +
	"\x11filterableEntries\x18\x03 \x03(\v2\x18.mdining.FilterableEntryR\x11filterableEntries\x1aG\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.mdining.ItemR\x05value:\x028\x01\"U\n" +
	"\vMenuRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04meal\x18\x02 \x01(\tR\x04meal\x12\x1e\n" +
	"\n" +
	"diningHall\x18\x03 \x01(\tR\n" +
	"diningHall\"0\n" +
	"\tMenuReply\x12#\n" +
	"\x05menus\x18\x01 \x03(\v2\r.mdining.MenuR\x05menus\"m\n" +
	"\vFoodRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\"0\n" +
	"\tFoodReply\x12#\n" +
	"\x05foods\x18\x01 \x03(\v2\r.mdining.FoodR\x05foods\"#\n" +
	"\rHeartsRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\":\n" +
	"\vHeartsReply\x12+\n" +
	"\x06counts\x18\x01 \x03(\v2\x13.mdining.HeartCountR\x06counts2\xa2\a\n" +
	"\aMDining\x12a\n" +
	"\x0eGetDiningHalls\x12\x1b.mdining.DiningHallsRequest\x1a\x19.mdining.DiningHallsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/diningHalls\x12I\n" +
	"\bGetItems\x12\x15.mdining.ItemsRequest\x1a\x13.mdining.ItemsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12y\n" +
	"\x14GetFilterableEntries\x12!.mdining.FilterableEntriesRequest\x1a\x1f.mdining.FilterableEntriesReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/filterableEntries\x12A\n" +
	"\x06GetAll\x12\x13.mdining.AllRequest\x1a\x11.mdining.AllReply\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/all\x12F\n" +
	"\aGetMenu\x12\x14.mdining.MenuRequest\x1a\x12.mdining.MenuReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/menus\x12F\n" +
	"\aGetFood\x12\x14.mdining.FoodRequest\x1a\x12.mdining.FoodReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/foods\x12U\n" +
	"\fGetFoodStats\x12\x19.mdining.FoodStatsRequest\x1a\x17.mdining.FoodStatsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/stats\x12e\n" +
	"\x0fGetSummaryStats\x12\x1c.mdining.SummaryStatsRequest\x1a\x1a.mdining.SummaryStatsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/summarystats\x12@\n" +
	"\fStreamHearts\x12\x16.mdining.HeartsRequest\x1a\x14.mdining.HeartsReply\"\x000\x01\x12M\n" +
	"\tGetHearts\x12\x16.mdining.HeartsRequest\x1a\x14.mdining.HeartsReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/hearts\x12L\n" +
	"\bAddHeart\x12\x16.mdining.HeartsRequest\x1a\x14.mdining.HeartsReply\"\x12\x82\xd3\xe4\x93\x02\f\"\n" +
	"/v1/heartsb\x06proto3"

var (
	file_proto_mdining_proto_rawDescOnce sync.Once
	file_proto_mdining_proto_rawDescData []byte
)

func file_proto_mdining_proto_rawDescGZIP() []byte {
	file_proto_mdining_proto_rawDescOnce.Do(func() {
		file_proto_mdining_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mdining_proto_rawDesc), len(file_proto_mdining_proto_rawDesc)))
	})
	return file_proto_mdining_proto_rawDescData
}

var file_proto_mdining_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_mdining_proto_goTypes = []any{
	(*FoodStatsRequest)(nil),         // 0: mdining.FoodStatsRequest
	(*FoodStatsReply)(nil),           // 1: mdining.FoodStatsReply
	(*SummaryStatsRequest)(nil),      // 2: mdining.SummaryStatsRequest
	(*SummaryStatsReply)(nil),        // 3: mdining.SummaryStatsReply
	(*DiningHallsRequest)(nil),       // 4: mdining.DiningHallsRequest
	(*DiningHallsReply)(nil),         // 5: mdining.DiningHallsReply
	(*ItemsRequest)(nil),             // 6: mdining.ItemsRequest
	(*ItemsReply)(nil),               // 7: mdining.ItemsReply
	(*FilterableEntriesRequest)(nil), // 8: mdining.FilterableEntriesRequest
	(*FilterableEntriesReply)(nil),   // 9: mdining.FilterableEntriesReply
	(*AllRequest)(nil),               // 10: mdining.AllRequest
	(*AllReply)(nil),                 // 11: mdining.AllReply
	(*MenuRequest)(nil),              // 12: mdining.MenuRequest
	(*MenuReply)(nil),                // 13: mdining.MenuReply
	(*FoodRequest)(nil),              // 14: mdining.FoodRequest
	(*FoodReply)(nil),                // 15: mdining.FoodReply
	(*HeartsRequest)(nil),            // 16: mdining.HeartsRequest
	(*HeartsReply)(nil),              // 17: mdining.HeartsReply
	nil,                              // 18: mdining.ItemsReply.ItemsEntry
	nil,                              // 19: mdining.AllReply.ItemsEntry
	(*FoodStat)(nil),                 // 20: mdining.FoodStat
	(*SummaryStats)(nil),             // 21: mdining.SummaryStats
	(*DiningHall)(nil),               // 22: mdining.DiningHall
	(*FilterableEntry)(nil),          // 23: mdining.FilterableEntry
	(*Menu)(nil),                     // 24: mdining.Menu
	(*Food)(nil),                     // 25: mdining.Food
	(*HeartCount)(nil),               // 26: mdining.HeartCount
	(*Item)(nil),                     // 27: mdining.Item
}
var file_proto_mdining_proto_depIdxs = []int32{
	20, // 0: mdining.FoodStatsReply.foodStats:type_name -> mdining.FoodStat
	21, // 1: mdining.SummaryStatsReply.stats:type_name -> mdining.SummaryStats
	22, // 2: mdining.DiningHallsReply.diningHalls:type_name -> mdining.DiningHall
	18, // 3: mdining.ItemsReply.items:type_name -> mdining.ItemsReply.ItemsEntry
	23, // 4: mdining.FilterableEntriesReply.filterableEntries:type_name -> mdining.FilterableEntry
	22, // 5: mdining.AllReply.diningHalls:type_name -> mdining.DiningHall
	19, // 6: mdining.AllReply.items:type_name -> mdining.AllReply.ItemsEntry
	23, // 7: mdining.AllReply.filterableEntries:type_name -> mdining.FilterableEntry
	24, // 8: mdining.MenuReply.menus:type_name -> mdining.Menu
	25, // 9: mdining.FoodReply.foods:type_name -> mdining.Food
	26, // 10: mdining.HeartsReply.counts:type_name -> mdining.HeartCount
	27, // 11: mdining.ItemsReply.ItemsEntry.value:type_name -> mdining.Item
	27, // 12: mdining.AllReply.ItemsEntry.value:type_name -> mdining.Item
	4,  // 13: mdining.MDining.GetDiningHalls:input_type -> mdining.DiningHallsRequest
	6,  // 14: mdining.MDining.GetItems:input_type -> mdining.ItemsRequest
	8,  // 15: mdining.MDining.GetFilterableEntries:input_type -> mdining.FilterableEntriesRequest
	10, // 16: mdining.MDining.GetAll:input_type -> mdining.AllRequest
	12, // 17: mdining.MDining.GetMenu:input_type -> mdining.MenuRequest
	14, // 18: mdining.MDining.GetFood:input_type -> mdining.FoodRequest
	0,  // 19: mdining.MDining.GetFoodStats:input_type -> mdining.FoodStatsRequest
	2,  // 20: mdining.MDining.GetSummaryStats:input_type -> mdining.SummaryStatsRequest
	16, // 21: mdining.MDining.StreamHearts:input_type -> mdining.HeartsRequest
	16, // 22: mdining.MDining.GetHearts:input_type -> mdining.HeartsRequest
	16, // 23: mdining.MDining.AddHeart:input_type -> mdining.HeartsRequest
	5,  // 24: mdining.MDining.GetDiningHalls:output_type -> mdining.DiningHallsReply
	7,  // 25: mdining.MDining.GetItems:output_type -> mdining.ItemsReply
	9,  // 26: mdining.MDining.GetFilterableEntries:output_type -> mdining.FilterableEntriesReply
	11, // 27: mdining.MDining.GetAll:output_type -> mdining.AllReply
	13, // 28: mdining.MDining.GetMenu:output_type -> mdining.MenuReply
	15, // 29: mdining.MDining.GetFood:output_type -> mdining.FoodReply
	1,  // 30: mdining.MDining.GetFoodStats:output_type -> mdining.FoodStatsReply
	3,  // 31: mdining.MDining.GetSummaryStats:output_type -> mdining.SummaryStatsReply
	17, // 32: mdining.MDining.StreamHearts:output_type -> mdining.HeartsReply
	17, // 33: mdining.MDining.GetHearts:output_type -> mdining.HeartsReply
	17, // 34: mdining.MDining.AddHeart:output_type -> mdining.HeartsReply
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_mdining_proto_init() }
func file_proto_mdining_proto_init() {
	if File_proto_mdining_proto != nil {
		return
	}
	file_proto_dininghalls_proto_init()
	file_proto_items_proto_init()
	file_proto_filterableentries_proto_init()
	file_proto_menu_proto_init()
	file_proto_food_proto_init()
	file_proto_foodstat_proto_init()
	file_proto_hearts_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mdining_proto_rawDesc), len(file_proto_mdining_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mdining_proto_goTypes,
		DependencyIndexes: file_proto_mdining_proto_depIdxs,
		MessageInfos:      file_proto_mdining_proto_msgTypes,
	}.Build()
	File_proto_mdining_proto = out.File
	file_proto_mdining_proto_goTypes = nil
	file_proto_mdining_proto_depIdxs = nil
}
