// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/mdining.proto

package mdining

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MDining_GetDiningHalls_FullMethodName       = "/mdining.MDining/GetDiningHalls"
	MDining_GetItems_FullMethodName             = "/mdining.MDining/GetItems"
	MDining_GetFilterableEntries_FullMethodName = "/mdining.MDining/GetFilterableEntries"
	MDining_GetAll_FullMethodName               = "/mdining.MDining/GetAll"
	MDining_GetMenu_FullMethodName              = "/mdining.MDining/GetMenu"
	MDining_GetFood_FullMethodName              = "/mdining.MDining/GetFood"
	MDining_GetFoodStats_FullMethodName         = "/mdining.MDining/GetFoodStats"
	MDining_GetSummaryStats_FullMethodName      = "/mdining.MDining/GetSummaryStats"
	MDining_StreamHearts_FullMethodName         = "/mdining.MDining/StreamHearts"
	MDining_GetHearts_FullMethodName            = "/mdining.MDining/GetHearts"
	MDining_AddHeart_FullMethodName             = "/mdining.MDining/AddHeart"
)

// MDiningClient is the client API for MDining service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDiningClient interface {
	GetDiningHalls(ctx context.Context, in *DiningHallsRequest, opts ...grpc.CallOption) (*DiningHallsReply, error)
	GetItems(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsReply, error)
	GetFilterableEntries(ctx context.Context, in *FilterableEntriesRequest, opts ...grpc.CallOption) (*FilterableEntriesReply, error)
	GetAll(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllReply, error)
	GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuReply, error)
	GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodReply, error)
	GetFoodStats(ctx context.Context, in *FoodStatsRequest, opts ...grpc.CallOption) (*FoodStatsReply, error)
	GetSummaryStats(ctx context.Context, in *SummaryStatsRequest, opts ...grpc.CallOption) (*SummaryStatsReply, error)
	StreamHearts(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeartsReply], error)
	GetHearts(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (*HeartsReply, error)
	AddHeart(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (*HeartsReply, error)
}

type mDiningClient struct {
	cc grpc.ClientConnInterface
}

func NewMDiningClient(cc grpc.ClientConnInterface) MDiningClient {
	return &mDiningClient{cc}
}

func (c *mDiningClient) GetDiningHalls(ctx context.Context, in *DiningHallsRequest, opts ...grpc.CallOption) (*DiningHallsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiningHallsReply)
	err := c.cc.Invoke(ctx, MDining_GetDiningHalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetItems(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemsReply)
	err := c.cc.Invoke(ctx, MDining_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetFilterableEntries(ctx context.Context, in *FilterableEntriesRequest, opts ...grpc.CallOption) (*FilterableEntriesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterableEntriesReply)
	err := c.cc.Invoke(ctx, MDining_GetFilterableEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetAll(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllReply)
	err := c.cc.Invoke(ctx, MDining_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuReply)
	err := c.cc.Invoke(ctx, MDining_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodReply)
	err := c.cc.Invoke(ctx, MDining_GetFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetFoodStats(ctx context.Context, in *FoodStatsRequest, opts ...grpc.CallOption) (*FoodStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodStatsReply)
	err := c.cc.Invoke(ctx, MDining_GetFoodStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) GetSummaryStats(ctx context.Context, in *SummaryStatsRequest, opts ...grpc.CallOption) (*SummaryStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryStatsReply)
	err := c.cc.Invoke(ctx, MDining_GetSummaryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) StreamHearts(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeartsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MDining_ServiceDesc.Streams[0], MDining_StreamHearts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartsRequest, HeartsReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDining_StreamHeartsClient = grpc.ServerStreamingClient[HeartsReply]

func (c *mDiningClient) GetHearts(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (*HeartsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartsReply)
	err := c.cc.Invoke(ctx, MDining_GetHearts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDiningClient) AddHeart(ctx context.Context, in *HeartsRequest, opts ...grpc.CallOption) (*HeartsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartsReply)
	err := c.cc.Invoke(ctx, MDining_AddHeart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDiningServer is the server API for MDining service.
// All implementations should embed UnimplementedMDiningServer
// for forward compatibility.
type MDiningServer interface {
	GetDiningHalls(context.Context, *DiningHallsRequest) (*DiningHallsReply, error)
	GetItems(context.Context, *ItemsRequest) (*ItemsReply, error)
	GetFilterableEntries(context.Context, *FilterableEntriesRequest) (*FilterableEntriesReply, error)
	GetAll(context.Context, *AllRequest) (*AllReply, error)
	GetMenu(context.Context, *MenuRequest) (*MenuReply, error)
	GetFood(context.Context, *FoodRequest) (*FoodReply, error)
	GetFoodStats(context.Context, *FoodStatsRequest) (*FoodStatsReply, error)
	GetSummaryStats(context.Context, *SummaryStatsRequest) (*SummaryStatsReply, error)
	StreamHearts(*HeartsRequest, grpc.ServerStreamingServer[HeartsReply]) error
	GetHearts(context.Context, *HeartsRequest) (*HeartsReply, error)
	AddHeart(context.Context, *HeartsRequest) (*HeartsReply, error)
}

// UnimplementedMDiningServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMDiningServer struct{}

func (UnimplementedMDiningServer) GetDiningHalls(context.Context, *DiningHallsRequest) (*DiningHallsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiningHalls not implemented")
}
func (UnimplementedMDiningServer) GetItems(context.Context, *ItemsRequest) (*ItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedMDiningServer) GetFilterableEntries(context.Context, *FilterableEntriesRequest) (*FilterableEntriesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilterableEntries not implemented")
}
func (UnimplementedMDiningServer) GetAll(context.Context, *AllRequest) (*AllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedMDiningServer) GetMenu(context.Context, *MenuRequest) (*MenuReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedMDiningServer) GetFood(context.Context, *FoodRequest) (*FoodReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFood not implemented")
}
func (UnimplementedMDiningServer) GetFoodStats(context.Context, *FoodStatsRequest) (*FoodStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFoodStats not implemented")
}
func (UnimplementedMDiningServer) GetSummaryStats(context.Context, *SummaryStatsRequest) (*SummaryStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummaryStats not implemented")
}
func (UnimplementedMDiningServer) StreamHearts(*HeartsRequest, grpc.ServerStreamingServer[HeartsReply]) error {
	return status.Error(codes.Unimplemented, "method StreamHearts not implemented")
}
func (UnimplementedMDiningServer) GetHearts(context.Context, *HeartsRequest) (*HeartsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHearts not implemented")
}
func (UnimplementedMDiningServer) AddHeart(context.Context, *HeartsRequest) (*HeartsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHeart not implemented")
}
func (UnimplementedMDiningServer) testEmbeddedByValue() {}

// UnsafeMDiningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDiningServer will
// result in compilation errors.
type UnsafeMDiningServer interface {
	mustEmbedUnimplementedMDiningServer()
}

func RegisterMDiningServer(s grpc.ServiceRegistrar, srv MDiningServer) {
	// If the following call panics, it indicates UnimplementedMDiningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MDining_ServiceDesc, srv)
}

func _MDining_GetDiningHalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiningHallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetDiningHalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetDiningHalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetDiningHalls(ctx, req.(*DiningHallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetItems(ctx, req.(*ItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetFilterableEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterableEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetFilterableEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetFilterableEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetFilterableEntries(ctx, req.(*FilterableEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetAll(ctx, req.(*AllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetFood(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetFoodStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetFoodStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetFoodStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetFoodStats(ctx, req.(*FoodStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_GetSummaryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetSummaryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetSummaryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetSummaryStats(ctx, req.(*SummaryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_StreamHearts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeartsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDiningServer).StreamHearts(m, &grpc.GenericServerStream[HeartsRequest, HeartsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDining_StreamHeartsServer = grpc.ServerStreamingServer[HeartsReply]

func _MDining_GetHearts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).GetHearts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_GetHearts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).GetHearts(ctx, req.(*HeartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDining_AddHeart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDiningServer).AddHeart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDining_AddHeart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDiningServer).AddHeart(ctx, req.(*HeartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDining_ServiceDesc is the grpc.ServiceDesc for MDining service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDining_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdining.MDining",
	HandlerType: (*MDiningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiningHalls",
			Handler:    _MDining_GetDiningHalls_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _MDining_GetItems_Handler,
		},
		{
			MethodName: "GetFilterableEntries",
			Handler:    _MDining_GetFilterableEntries_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _MDining_GetAll_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _MDining_GetMenu_Handler,
		},
		{
			MethodName: "GetFood",
			Handler:    _MDining_GetFood_Handler,
		},
		{
			MethodName: "GetFoodStats",
			Handler:    _MDining_GetFoodStats_Handler,
		},
		{
			MethodName: "GetSummaryStats",
			Handler:    _MDining_GetSummaryStats_Handler,
		},
		{
			MethodName: "GetHearts",
			Handler:    _MDining_GetHearts_Handler,
		},
		{
			MethodName: "AddHeart",
			Handler:    _MDining_AddHeart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHearts",
			Handler:       _MDining_StreamHearts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mdining.proto",
}
