// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/menu.proto

package mdining

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Menu struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meal             string                 `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	Date             string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	FormattedDate    string                 `protobuf:"bytes,3,opt,name=formattedDate,proto3" json:"formattedDate,omitempty"`
	RatingCount      int32                  `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	RatingScore      int32                  `protobuf:"varint,5,opt,name=ratingScore,proto3" json:"ratingScore,omitempty"`
	HasCategories    bool                   `protobuf:"varint,6,opt,name=hasCategories,proto3" json:"hasCategories,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Category         []*Category            `protobuf:"bytes,8,rep,name=category,proto3" json:"category,omitempty"`
	DiningHallName   string                 `protobuf:"bytes,9,opt,name=diningHallName,proto3" json:"diningHallName,omitempty"`
	DiningHallMeal   string                 `protobuf:"bytes,10,opt,name=diningHallMeal,proto3" json:"diningHallMeal,omitempty"`
	DiningHallCampus string                 `protobuf:"bytes,11,opt,name=diningHallCampus,proto3" json:"diningHallCampus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_proto_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetMeal() string {
	if x != nil {
		return x.Meal
	}
	return ""
}

func (x *Menu) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Menu) GetFormattedDate() string {
	if x != nil {
		return x.FormattedDate
	}
	return ""
}

func (x *Menu) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *Menu) GetRatingScore() int32 {
	if x != nil {
		return x.RatingScore
	}
	return 0
}

func (x *Menu) GetHasCategories() bool {
	if x != nil {
		return x.HasCategories
	}
	return false
}

func (x *Menu) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Menu) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Menu) GetDiningHallName() string {
	if x != nil {
		return x.DiningHallName
	}
	return ""
}

func (x *Menu) GetDiningHallMeal() string {
	if x != nil {
		return x.DiningHallMeal
	}
	return ""
}

func (x *Menu) GetDiningHallCampus() string {
	if x != nil {
		return x.DiningHallCampus
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MenuItem      []*MenuItem            `protobuf:"bytes,2,rep,name=menuItem,proto3" json:"menuItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetMenuItem() []*MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attribute     []string               `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	RatingCount   int32                  `protobuf:"varint,3,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	RatingScore   int32                  `protobuf:"varint,4,opt,name=ratingScore,proto3" json:"ratingScore,omitempty"`
	Allergens     []string               `protobuf:"bytes,5,rep,name=allergens,proto3" json:"allergens,omitempty"`
	ItemSizes     []*ItemSizes           `protobuf:"bytes,6,rep,name=itemSizes,proto3" json:"itemSizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *MenuItem) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *MenuItem) GetRatingScore() int32 {
	if x != nil {
		return x.RatingScore
	}
	return 0
}

func (x *MenuItem) GetAllergens() []string {
	if x != nil {
		return x.Allergens
	}
	return nil
}

func (x *MenuItem) GetItemSizes() []*ItemSizes {
	if x != nil {
		return x.ItemSizes
	}
	return nil
}

type ItemSizes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PortionSize     int32                  `protobuf:"varint,1,opt,name=portionSize,proto3" json:"portionSize,omitempty"`
	ServingSize     string                 `protobuf:"bytes,2,opt,name=servingSize,proto3" json:"servingSize,omitempty"`
	NutritionalInfo []*NutritionalInfo     `protobuf:"bytes,3,rep,name=nutritionalInfo,proto3" json:"nutritionalInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ItemSizes) Reset() {
	*x = ItemSizes{}
	mi := &file_proto_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSizes) ProtoMessage() {}

func (x *ItemSizes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSizes.ProtoReflect.Descriptor instead.
func (*ItemSizes) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{3}
}

func (x *ItemSizes) GetPortionSize() int32 {
	if x != nil {
		return x.PortionSize
	}
	return 0
}

func (x *ItemSizes) GetServingSize() string {
	if x != nil {
		return x.ServingSize
	}
	return ""
}

func (x *ItemSizes) GetNutritionalInfo() []*NutritionalInfo {
	if x != nil {
		return x.NutritionalInfo
	}
	return nil
}

type NutritionalInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value             int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Units             string                 `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	PercentDailyValue int32                  `protobuf:"varint,4,opt,name=percentDailyValue,proto3" json:"percentDailyValue,omitempty"`
	Type              string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NutritionalInfo) Reset() {
	*x = NutritionalInfo{}
	mi := &file_proto_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionalInfo) ProtoMessage() {}

func (x *NutritionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionalInfo.ProtoReflect.Descriptor instead.
func (*NutritionalInfo) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{4}
}

func (x *NutritionalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NutritionalInfo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NutritionalInfo) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *NutritionalInfo) GetPercentDailyValue() int32 {
	if x != nil {
		return x.PercentDailyValue
	}
	return 0
}

func (x *NutritionalInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_menu_proto protoreflect.FileDescriptor

const file_proto_menu_proto_rawDesc = "" +
	"\n" +
	"\x10proto/menu.proto\x12\amdining\"\x8b\x03\n" +
	"\x04Menu\x12\x12\n" +
	"\x04meal\x18\x01 \x01(\tR\x04meal\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12$\n" +
	"\rformattedDate\x18\x03 \x01(\tR\rformattedDate\x12 \n" +
	"\vratingCount\x18\x04 \x01(\x05R\vratingCount\x12 \n" +
	"\vratingScore\x18\x05 \x01(\x05R\vratingScore\x12$\n" +
	"\rhasCategories\x18\x06 \x01(\bR\rhasCategories\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12-\n" +
	"\bcategory\x18\b \x03(\v2\x11.mdining.CategoryR\bcategory\x12&\n" +
	"\x0ediningHallName\x18\t \x01(\tR\x0ediningHallName\x12&\n" +
	"\x0ediningHallMeal\x18\n" +
	" \x01(\tR\x0ediningHallMeal\x12*\n" +
	"\x10diningHallCampus\x18\v \x01(\tR\x10diningHallCampus\"M\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\bmenuItem\x18\x02 \x03(\v2\x11.mdining.MenuItemR\bmenuItem\"\xd0\x01\n" +
	"\bMenuItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tattribute\x18\x02 \x03(\tR\tattribute\x12 \n" +
	"\vratingCount\x18\x03 \x01(\x05R\vratingCount\x12 \n" +
	"\vratingScore\x18\x04 \x01(\x05R\vratingScore\x12\x1c\n" +
	"\tallergens\x18\x05 \x03(\tR\tallergens\x120\n" +
	"\titemSizes\x18\x06 \x03(\v2\x12.mdining.ItemSizesR\titemSizes\"\x93\x01\n" +
	"\tItemSizes\x12 \n" +
	"\vportionSize\x18\x01 \x01(\x05R\vportionSize\x12 \n" +
	"\vservingSize\x18\x02 \x01(\tR\vservingSize\x12B\n" +
	"\x0fnutritionalInfo\x18\x03 \x03(\v2\x18.mdining.NutritionalInfoR\x0fnutritionalInfo\"\x93\x01\n" +
	"\x0fNutritionalInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x14\n" +
	"\x05units\x18\x03 \x01(\tR\x05units\x12,\n" +
	"\x11percentDailyValue\x18\x04 \x01(\x05R\x11percentDailyValue\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04typeb\x06proto3"

var (
	file_proto_menu_proto_rawDescOnce sync.Once
	file_proto_menu_proto_rawDescData []byte
)

func file_proto_menu_proto_rawDescGZIP() []byte {
	file_proto_menu_proto_rawDescOnce.Do(func() {
		file_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)))
	})
	return file_proto_menu_proto_rawDescData
}

var file_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_menu_proto_goTypes = []any{
	(*Menu)(nil),            // 0: mdining.Menu
	(*Category)(nil),        // 1: mdining.Category
	(*MenuItem)(nil),        // 2: mdining.MenuItem
	(*ItemSizes)(nil),       // 3: mdining.ItemSizes
	(*NutritionalInfo)(nil), // 4: mdining.NutritionalInfo
}
var file_proto_menu_proto_depIdxs = []int32{
	1, // 0: mdining.Menu.category:type_name -> mdining.Category
	2, // 1: mdining.Category.menuItem:type_name -> mdining.MenuItem
	3, // 2: mdining.MenuItem.itemSizes:type_name -> mdining.ItemSizes
	4, // 3: mdining.ItemSizes.nutritionalInfo:type_name -> mdining.NutritionalInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_menu_proto_init() }
func file_proto_menu_proto_init() {
	if File_proto_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_menu_proto_goTypes,
		DependencyIndexes: file_proto_menu_proto_depIdxs,
		MessageInfos:      file_proto_menu_proto_msgTypes,
	}.Build()
	File_proto_menu_proto = out.File
	file_proto_menu_proto_goTypes = nil
	file_proto_menu_proto_depIdxs = nil
}
