// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/mdiningapi2.proto

// These are protos for the mdining rest API (updated from original mdiningapi)

package mdiningapi2

import (
	mdining "github.com/MichiganDiningAPI/proto/mdining"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /dining/locations
type GetLocationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      []*Location            `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsReply) Reset() {
	*x = GetLocationsReply{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsReply) ProtoMessage() {}

func (x *GetLocationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsReply.ProtoReflect.Descriptor instead.
func (*GetLocationsReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{0}
}

func (x *GetLocationsReply) GetLocation() []*Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Location struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	Officialbuildingid    int32                                `protobuf:"varint,1,opt,name=officialbuildingid,proto3" json:"officialbuildingid,omitempty"`
	Lat                   float32                              `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                   float32                              `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Restricted            bool                                 `protobuf:"varint,4,opt,name=restricted,proto3" json:"restricted,omitempty"`
	Buildingpreferredname string                               `protobuf:"bytes,5,opt,name=buildingpreferredname,proto3" json:"buildingpreferredname,omitempty"`
	Campus                string                               `protobuf:"bytes,6,opt,name=campus,proto3" json:"campus,omitempty"`
	DisplayName           string                               `protobuf:"bytes,7,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Image                 string                               `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Name                  string                               `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Type                  string                               `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Contact               *Location_Contact                    `protobuf:"bytes,11,opt,name=contact,proto3" json:"contact,omitempty"`
	Address               *mdining.DiningHall_Building_Address `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetOfficialbuildingid() int32 {
	if x != nil {
		return x.Officialbuildingid
	}
	return 0
}

func (x *Location) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetRestricted() bool {
	if x != nil {
		return x.Restricted
	}
	return false
}

func (x *Location) GetBuildingpreferredname() string {
	if x != nil {
		return x.Buildingpreferredname
	}
	return ""
}

func (x *Location) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Location) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Location) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Location) GetContact() *Location_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Location) GetAddress() *mdining.DiningHall_Building_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// /dining/meal-hours?location=Bursley%20Dining%20Hall&date=13-10-2020
type GetMealHoursReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         []*Hours               `protobuf:"bytes,1,rep,name=hours,proto3" json:"hours,omitempty"`
	Meal          []*Meal                `protobuf:"bytes,2,rep,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealHoursReply) Reset() {
	*x = GetMealHoursReply{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealHoursReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealHoursReply) ProtoMessage() {}

func (x *GetMealHoursReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealHoursReply.ProtoReflect.Descriptor instead.
func (*GetMealHoursReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{2}
}

func (x *GetMealHoursReply) GetHours() []*Hours {
	if x != nil {
		return x.Hours
	}
	return nil
}

func (x *GetMealHoursReply) GetMeal() []*Meal {
	if x != nil {
		return x.Meal
	}
	return nil
}

type Hours struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventDayEnd    string                 `protobuf:"bytes,1,opt,name=event_day_end,json=eventDayEnd,proto3" json:"event_day_end,omitempty"`
	EventDayStart  string                 `protobuf:"bytes,2,opt,name=event_day_start,json=eventDayStart,proto3" json:"event_day_start,omitempty"`
	EventMaplink   string                 `protobuf:"bytes,3,opt,name=event_maplink,json=eventMaplink,proto3" json:"event_maplink,omitempty"`
	EventTimeEnd   string                 `protobuf:"bytes,4,opt,name=event_time_end,json=eventTimeEnd,proto3" json:"event_time_end,omitempty"`
	EventTimeStart string                 `protobuf:"bytes,5,opt,name=event_time_start,json=eventTimeStart,proto3" json:"event_time_start,omitempty"`
	EventTitle     string                 `protobuf:"bytes,6,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hours) Reset() {
	*x = Hours{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hours) ProtoMessage() {}

func (x *Hours) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hours.ProtoReflect.Descriptor instead.
func (*Hours) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{3}
}

func (x *Hours) GetEventDayEnd() string {
	if x != nil {
		return x.EventDayEnd
	}
	return ""
}

func (x *Hours) GetEventDayStart() string {
	if x != nil {
		return x.EventDayStart
	}
	return ""
}

func (x *Hours) GetEventMaplink() string {
	if x != nil {
		return x.EventMaplink
	}
	return ""
}

func (x *Hours) GetEventTimeEnd() string {
	if x != nil {
		return x.EventTimeEnd
	}
	return ""
}

func (x *Hours) GetEventTimeStart() string {
	if x != nil {
		return x.EventTimeStart
	}
	return ""
}

func (x *Hours) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

type Meal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMenu       bool                   `protobuf:"varint,1,opt,name=hasMenu,proto3" json:"hasMenu,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meal) Reset() {
	*x = Meal{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meal) ProtoMessage() {}

func (x *Meal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meal.ProtoReflect.Descriptor instead.
func (*Meal) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{4}
}

func (x *Meal) GetHasMenu() bool {
	if x != nil {
		return x.HasMenu
	}
	return false
}

func (x *Meal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// /dining/menu?location=Bursley%20Dining%20Hall&date=13-10-2020&meal=BREAKFAST
type GetMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *Menu                  `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuReply) Reset() {
	*x = GetMenuReply{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReply) ProtoMessage() {}

func (x *GetMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReply.ProtoReflect.Descriptor instead.
func (*GetMenuReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{5}
}

func (x *GetMenuReply) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      []*Category            `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{6}
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MenuItem      []*MenuItem            `protobuf:"bytes,2,rep,name=menuItem,proto3" json:"menuItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{7}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetMenuItem() []*MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attribute     []string               `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Allergens     []string               `protobuf:"bytes,3,rep,name=allergens,proto3" json:"allergens,omitempty"`
	ItemSizes     *ItemSizes             `protobuf:"bytes,4,opt,name=itemSizes,proto3" json:"itemSizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{8}
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *MenuItem) GetAllergens() []string {
	if x != nil {
		return x.Allergens
	}
	return nil
}

func (x *MenuItem) GetItemSizes() *ItemSizes {
	if x != nil {
		return x.ItemSizes
	}
	return nil
}

type ItemSizes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortionSize   string                 `protobuf:"bytes,1,opt,name=portion_size,json=portionSize,proto3" json:"portion_size,omitempty"`
	ServingSize   string                 `protobuf:"bytes,2,opt,name=serving_size,json=servingSize,proto3" json:"serving_size,omitempty"`
	Nutrition     []*NutritionalInfo     `protobuf:"bytes,3,rep,name=nutrition,proto3" json:"nutrition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSizes) Reset() {
	*x = ItemSizes{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSizes) ProtoMessage() {}

func (x *ItemSizes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSizes.ProtoReflect.Descriptor instead.
func (*ItemSizes) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{9}
}

func (x *ItemSizes) GetPortionSize() string {
	if x != nil {
		return x.PortionSize
	}
	return ""
}

func (x *ItemSizes) GetServingSize() string {
	if x != nil {
		return x.ServingSize
	}
	return ""
}

func (x *ItemSizes) GetNutrition() []*NutritionalInfo {
	if x != nil {
		return x.Nutrition
	}
	return nil
}

type NutritionalInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value             string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PercentDailyValue int32                  `protobuf:"varint,4,opt,name=percentDailyValue,proto3" json:"percentDailyValue,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NutritionalInfo) Reset() {
	*x = NutritionalInfo{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionalInfo) ProtoMessage() {}

func (x *NutritionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionalInfo.ProtoReflect.Descriptor instead.
func (*NutritionalInfo) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{10}
}

func (x *NutritionalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NutritionalInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NutritionalInfo) GetPercentDailyValue() int32 {
	if x != nil {
		return x.PercentDailyValue
	}
	return 0
}

// /dining/capacity
type GetCapacityReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      []*Capacity            `protobuf:"bytes,1,rep,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityReply) Reset() {
	*x = GetCapacityReply{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityReply) ProtoMessage() {}

func (x *GetCapacityReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityReply.ProtoReflect.Descriptor instead.
func (*GetCapacityReply) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{11}
}

func (x *GetCapacityReply) GetCapacity() []*Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapacityCount string                 `protobuf:"bytes,1,opt,name=capacity_count,json=capacityCount,proto3" json:"capacity_count,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Patronflow    string                 `protobuf:"bytes,3,opt,name=patronflow,proto3" json:"patronflow,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Timelaps      string                 `protobuf:"bytes,5,opt,name=timelaps,proto3" json:"timelaps,omitempty"`
	Total         string                 `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{12}
}

func (x *Capacity) GetCapacityCount() string {
	if x != nil {
		return x.CapacityCount
	}
	return ""
}

func (x *Capacity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capacity) GetPatronflow() string {
	if x != nil {
		return x.Patronflow
	}
	return ""
}

func (x *Capacity) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Capacity) GetTimelaps() string {
	if x != nil {
		return x.Timelaps
	}
	return ""
}

func (x *Capacity) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type Location_Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location_Contact) Reset() {
	*x = Location_Contact{}
	mi := &file_proto_mdiningapi2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location_Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location_Contact) ProtoMessage() {}

func (x *Location_Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdiningapi2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location_Contact.ProtoReflect.Descriptor instead.
func (*Location_Contact) Descriptor() ([]byte, []int) {
	return file_proto_mdiningapi2_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Location_Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Location_Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_mdiningapi2_proto protoreflect.FileDescriptor

const file_proto_mdiningapi2_proto_rawDesc = "" +
	"\n" +
	"\x17proto/mdiningapi2.proto\x12\vmdiningapi2\x1a\x17proto/dininghalls.proto\"F\n" +
	"\x11GetLocationsReply\x121\n" +
	"\blocation\x18\x01 \x03(\v2\x15.mdiningapi2.LocationR\blocation\"\xdc\x03\n" +
	"\bLocation\x12.\n" +
	"\x12officialbuildingid\x18\x01 \x01(\x05R\x12officialbuildingid\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x02R\x03lng\x12\x1e\n" +
	"\n" +
	"restricted\x18\x04 \x01(\bR\n" +
	"restricted\x124\n" +
	"\x15buildingpreferredname\x18\x05 \x01(\tR\x15buildingpreferredname\x12\x16\n" +
	"\x06campus\x18\x06 \x01(\tR\x06campus\x12 \n" +
	"\vdisplayName\x18\a \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x127\n" +
	"\acontact\x18\v \x01(\v2\x1d.mdiningapi2.Location.ContactR\acontact\x12>\n" +
	"\aaddress\x18\f \x01(\v2$.mdining.DiningHall.Building.AddressR\aaddress\x1a5\n" +
	"\aContact\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"d\n" +
	"\x11GetMealHoursReply\x12(\n" +
	"\x05hours\x18\x01 \x03(\v2\x12.mdiningapi2.HoursR\x05hours\x12%\n" +
	"\x04meal\x18\x02 \x03(\v2\x11.mdiningapi2.MealR\x04meal\"\xe9\x01\n" +
	"\x05Hours\x12\"\n" +
	"\revent_day_end\x18\x01 \x01(\tR\veventDayEnd\x12&\n" +
	"\x0fevent_day_start\x18\x02 \x01(\tR\reventDayStart\x12#\n" +
	"\revent_maplink\x18\x03 \x01(\tR\feventMaplink\x12$\n" +
	"\x0eevent_time_end\x18\x04 \x01(\tR\feventTimeEnd\x12(\n" +
	"\x10event_time_start\x18\x05 \x01(\tR\x0eeventTimeStart\x12\x1f\n" +
	"\vevent_title\x18\x06 \x01(\tR\n" +
	"eventTitle\"V\n" +
	"\x04Meal\x12\x18\n" +
	"\ahasMenu\x18\x01 \x01(\bR\ahasMenu\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"5\n" +
	"\fGetMenuReply\x12%\n" +
	"\x04menu\x18\x01 \x01(\v2\x11.mdiningapi2.MenuR\x04menu\"M\n" +
	"\x04Menu\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\bcategory\x18\x02 \x03(\v2\x15.mdiningapi2.CategoryR\bcategory\"Q\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\bmenuItem\x18\x02 \x03(\v2\x15.mdiningapi2.MenuItemR\bmenuItem\"\x90\x01\n" +
	"\bMenuItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tattribute\x18\x02 \x03(\tR\tattribute\x12\x1c\n" +
	"\tallergens\x18\x03 \x03(\tR\tallergens\x124\n" +
	"\titemSizes\x18\x04 \x01(\v2\x16.mdiningapi2.ItemSizesR\titemSizes\"\x8d\x01\n" +
	"\tItemSizes\x12!\n" +
	"\fportion_size\x18\x01 \x01(\tR\vportionSize\x12!\n" +
	"\fserving_size\x18\x02 \x01(\tR\vservingSize\x12:\n" +
	"\tnutrition\x18\x03 \x03(\v2\x1c.mdiningapi2.NutritionalInfoR\tnutrition\"i\n" +
	"\x0fNutritionalInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12,\n" +
	"\x11percentDailyValue\x18\x04 \x01(\x05R\x11percentDailyValue\"E\n" +
	"\x10GetCapacityReply\x121\n" +
	"\bcapacity\x18\x01 \x03(\v2\x15.mdiningapi2.CapacityR\bcapacity\"\xaf\x01\n" +
	"\bCapacity\x12%\n" +
	"\x0ecapacity_count\x18\x01 \x01(\tR\rcapacityCount\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"patronflow\x18\x03 \x01(\tR\n" +
	"patronflow\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\x12\x1a\n" +
	"\btimelaps\x18\x05 \x01(\tR\btimelaps\x12\x14\n" +
	"\x05total\x18\x06 \x01(\tR\x05totalb\x06proto3"

var (
	file_proto_mdiningapi2_proto_rawDescOnce sync.Once
	file_proto_mdiningapi2_proto_rawDescData []byte
)

func file_proto_mdiningapi2_proto_rawDescGZIP() []byte {
	file_proto_mdiningapi2_proto_rawDescOnce.Do(func() {
		file_proto_mdiningapi2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mdiningapi2_proto_rawDesc), len(file_proto_mdiningapi2_proto_rawDesc)))
	})
	return file_proto_mdiningapi2_proto_rawDescData
}

var file_proto_mdiningapi2_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_mdiningapi2_proto_goTypes = []any{
	(*GetLocationsReply)(nil),                   // 0: mdiningapi2.GetLocationsReply
	(*Location)(nil),                            // 1: mdiningapi2.Location
	(*GetMealHoursReply)(nil),                   // 2: mdiningapi2.GetMealHoursReply
	(*Hours)(nil),                               // 3: mdiningapi2.Hours
	(*Meal)(nil),                                // 4: mdiningapi2.Meal
	(*GetMenuReply)(nil),                        // 5: mdiningapi2.GetMenuReply
	(*Menu)(nil),                                // 6: mdiningapi2.Menu
	(*Category)(nil),                            // 7: mdiningapi2.Category
	(*MenuItem)(nil),                            // 8: mdiningapi2.MenuItem
	(*ItemSizes)(nil),                           // 9: mdiningapi2.ItemSizes
	(*NutritionalInfo)(nil),                     // 10: mdiningapi2.NutritionalInfo
	(*GetCapacityReply)(nil),                    // 11: mdiningapi2.GetCapacityReply
	(*Capacity)(nil),                            // 12: mdiningapi2.Capacity
	(*Location_Contact)(nil),                    // 13: mdiningapi2.Location.Contact
	(*mdining.DiningHall_Building_Address)(nil), // 14: mdining.DiningHall.Building.Address
}
var file_proto_mdiningapi2_proto_depIdxs = []int32{
	1,  // 0: mdiningapi2.GetLocationsReply.location:type_name -> mdiningapi2.Location
	13, // 1: mdiningapi2.Location.contact:type_name -> mdiningapi2.Location.Contact
	14, // 2: mdiningapi2.Location.address:type_name -> mdining.DiningHall.Building.Address
	3,  // 3: mdiningapi2.GetMealHoursReply.hours:type_name -> mdiningapi2.Hours
	4,  // 4: mdiningapi2.GetMealHoursReply.meal:type_name -> mdiningapi2.Meal
	6,  // 5: mdiningapi2.GetMenuReply.menu:type_name -> mdiningapi2.Menu
	7,  // 6: mdiningapi2.Menu.category:type_name -> mdiningapi2.Category
	8,  // 7: mdiningapi2.Category.menuItem:type_name -> mdiningapi2.MenuItem
	9,  // 8: mdiningapi2.MenuItem.itemSizes:type_name -> mdiningapi2.ItemSizes
	10, // 9: mdiningapi2.ItemSizes.nutrition:type_name -> mdiningapi2.NutritionalInfo
	12, // 10: mdiningapi2.GetCapacityReply.capacity:type_name -> mdiningapi2.Capacity
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_mdiningapi2_proto_init() }
func file_proto_mdiningapi2_proto_init() {
	if File_proto_mdiningapi2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mdiningapi2_proto_rawDesc), len(file_proto_mdiningapi2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mdiningapi2_proto_goTypes,
		DependencyIndexes: file_proto_mdiningapi2_proto_depIdxs,
		MessageInfos:      file_proto_mdiningapi2_proto_msgTypes,
	}.Build()
	File_proto_mdiningapi2_proto = out.File
	file_proto_mdiningapi2_proto_goTypes = nil
	file_proto_mdiningapi2_proto_depIdxs = nil
}
